CleverCloud/clever-components

- components/atoms/cc-button.js
- components/env-var/env-var-create.js
- components/env-var/env-var-form.js
- components/env-var/env-var-input.js
- components/translations/translations.en.js
- components/translations/translations.fr.js
- docs/adr-0001-why-do-we-wrap-button-clicks.md
- stories/atoms/cc-button.stories.js
- stories/lib/dom.js
> <cc-button> Add warning state and delay mechanism

- .gitlab-ci.yml
This is done on private internal GitLab and GitLab runner.
> Introduce .gitlab-ci.yml to enable feature-branch preview apps

- components/index.js
- components/infos/cc-infos-instances.js
- components/infos/running.svg
- components/infos/starting.svg
- components/lib/animate.js
- components/styles/infos.js
- components/translations/translations.en.js
- components/translations/translations.fr.js
- package-lock.json
- package.json
- stories/infos/cc-infos-instances.stories.js
- stories/lib/sequence.js
- tasks/minify-components.js
> cc-infos-instances: init component

- components/index.js
- components/info-tiles/cc-info-scalability.js
- components/translations/translations.en.js
- components/translations/translations.fr.js
- stories/info-tiles/cc-info-scalability.stories.js
> cc-info-scalability: init component

- components/index.js
- components/info-tiles/cc-info-consumption.js
- components/translations/translations.en.js
- components/translations/translations.fr.js
- stories/info-tiles/cc-info-consumption.stories.js
- stories/info-tiles/cc-info-deployments.stories.js
> cc-info-consumption: init component

- components/maps/cc-logsmap.js
- components/maps/cc-map.js
- components/translations/translations.en.js
- components/translations/translations.fr.js
- stories/maps/cc-logsmap.stories.js
- stories/maps/cc-map.stories.js
> cc-map and cc-logsmap: empty heatmap message and better legends

- WEB-COMPONENTS.md
- components/atoms/cc-button.js
- components/atoms/cc-datetime-relative.js
- components/atoms/cc-expand.js
- components/atoms/cc-img.js
- components/atoms/cc-input-text.js
- components/atoms/cc-loader.js
- components/atoms/cc-toggle.js
- components/env-var/env-var-create.js
- components/env-var/env-var-editor-expert.js
- components/env-var/env-var-editor-simple.js
- components/env-var/env-var-form.js
- components/env-var/env-var-full.js
- components/env-var/env-var-input.js
- components/maps/cc-logsmap.js
- components/maps/cc-map.js
- components/overview/cc-header-app.js
- components/overview/cc-header-orga.js
- components/overview/cc-overview.js
- components/overview/cc-tile-consumption.js
- components/overview/cc-tile-deployments.js
- components/overview/cc-tile-instances.js
- components/overview/cc-tile-requests.js
- components/overview/cc-tile-scalability.js
- components/overview/cc-tile-status-codes.js
- docs/ExampleComponent.js
- package-lock.json
- package.json
For now we're using the alpha of web-component-analyzer but it's a build/doc dep so I'd say it's OK since it works way better than the current stable we were using.
> Update web-component-analyzer and all our component's docs

- components/atoms/cc-input-text.js
- stories/atoms/cc-input-text.stories.js
> cc-input-text: fix hover behaviour on clipboard/secret buttons

- package.json
Related to #84
Signed-off-by: Antoine Leblanc <ant.leblanc@gmail.com>
> Fix repository URL into package.json

- src/atoms/cc-expand.js
> cc-expand: fix spring effect

- rollup-common.js
- src/saas/cc-heptapod-info.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/saas/cc-heptapod-info.stories.js
This adds a component `saas/cc-heptapod-info`. It needs to stay WIP until we are sure of the data we receive from the backend.
> Add saas/cc-heptapod-info component

- src/addon/cc-addon-elasticsearch-options.js
- src/addon/cc-addon-option-form.js
- src/addon/cc-addon-option.js
- src/saas/cc-heptapod-info.js
- stories/addon/cc-addon-option-form.stories.js
- stories/addon/cc-addon-option.stories.js
This fixes some import. And some lint issues.
> <cc-addon-elasticsearch-options>: fix imports

- CHANGELOG.md
- src/addon/cc-addon-elasticsearch-options.js
- src/addon/cc-addon-mongodb-options.js
- src/addon/cc-addon-mysql-options.js
- src/addon/cc-addon-option-form.js
- src/addon/cc-addon-postgresql-options.js
- src/assets/encryption-at-rest.svg
- src/templates/cc-addon-encryption-at-rest-option.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/addon/cc-addon-elasticsearch-options.stories.js
- stories/addon/cc-addon-mongodb-options.stories.js
- stories/addon/cc-addon-mysql-options.stories.js
- stories/addon/cc-addon-postgresql-options.stories.js
> Add encryption option and components for PostgreSQL, MySQL, MongoDB

- CHANGELOG.md
- src/lib/i18n-number.js
- test/i18n-number.test.js
> Fix prepareNumberUnitFormatter (handle 0 properly)

- CHANGELOG.md
- src/addon/cc-addon-elasticsearch-options.js
- src/addon/cc-addon-jenkins-options.js
- src/addon/cc-addon-redis-options.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/addon/cc-addon-elasticsearch-options.stories.js
- stories/addon/cc-addon-jenkins-options.stories.js
- stories/addon/cc-addon-redis-options.stories.js
⚠️ This needs https://github.com/CleverCloud/clever-components/pull/193 first. This PR will stay WIP until 193 is merged
This adds options for Redis and Jenkins add-ons and add the encryption option for Elasticsearch.
> Add-ons options for Redis and Jenkins, encryption option for elasticsearch

- docs/cc-example-component.js
- src/addon/cc-addon-admin.js
- src/atoms/cc-button.js
- src/atoms/cc-img.js
- src/atoms/cc-input-text.js
- src/env-var/cc-env-var-editor-expert.js
- src/env-var/cc-env-var-form.js
- src/lib/utils.js
- src/maps/cc-map-marker-dot.js
- src/maps/cc-map.js
- src/overview/cc-header-app.js
- src/overview/cc-tile-requests.js
- src/overview/cc-tile-status-codes.js
- src/zones/cc-zone-input.js
> Use LitElement's update (or updated) lifecycle callback instead of get/set

- CHANGELOG.md
- src/assets/decrement.svg
- src/assets/increment.svg
- src/atoms/cc-input-number.js
- stories/atoms/cc-input-number.stories.js
> <cc-input-number>

- CHANGELOG.md
- src/atoms/cc-input-number.js
- stories/atoms/cc-input-number.stories.js
> cc-input-number: controls mode disabled opacity

- CHANGELOG.md
- src/atoms/cc-input-number.js
- src/atoms/cc-input-text.js
- src/env-var/cc-env-var-create.js
- src/env-var/cc-env-var-editor-expert.js
- src/env-var/cc-env-var-input.js
- src/invoices/cc-invoice-table.js
- src/styles/default-theme.js
- src/tcp-redirections/cc-tcp-redirection-form.js
- src/tcp-redirections/cc-tcp-redirection.js
- src/zones/cc-zone.js
Fixes #233 will have to be followed by other issues later.
> Introduce `defaultThemeStyles` with monospace font-family

- .eslintrc.cjs
- CHANGELOG.md
- docs/guides/how-to-translate-and-localize.md
- docs/translations.example.js
- eslint-rules/i18n-always-arrow-with-sanitize.js
- eslint-rules/i18n-always-sanitize-with-html.js
- eslint-rules/i18n-no-paramless-arrow.js
- eslint-rules/i18n-no-sanitize-without-html.js
- eslint-rules/i18n-order.js
- eslint-rules/i18n-shared.js
- eslint-rules/i18n-valid-key.js
- eslint-rules/i18n-valid-value.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
> eslint: add custom rules "i18n-" to validate translations

- CHANGELOG.md
- src/pricing/cc-pricing-product.js
- src/pricing/cc-pricing-table.js
- stories/pricing/cc-pricing-product.stories.js
- stories/pricing/cc-pricing-table.stories.js
> Adapt cc-pricing-product for the docs

- CHANGELOG.md
- package-lock.json
- rollup/rollup-common.js
- src/lib/leaflet-esm.js
- src/lib/leaflet-heat.js
- src/lib/leaflet-pre-heat.js
- src/maps/cc-map.js
- web-dev-server.config.js
> cc-map: use leaflet from ESM source to improve treeshaking

- docs/references/browser-support.reference.md
Changed 2 links that were pointing to the french documentation
> Wrong documentation language

- CHANGELOG.md
- src/lib/product.js
- src/pricing/cc-pricing-product-storage.js
- src/pricing/cc-pricing-product.js
- src/pricing/cc-pricing-product.smart-addon.js
- src/pricing/cc-pricing-product.smart-runtime.js
- src/pricing/cc-pricing-table.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/assets/addon-plans.js
- stories/assets/runtime-plans.js
- stories/pricing/cc-pricing-product.stories.js
- stories/pricing/cc-pricing-table.stories.js
> cc-pricing-*: rename item to plan

- CHANGELOG.md
- src/addon/cc-elasticsearch-info.js
- src/molecules/cc-block.js
- stories/molecules/cc-block.stories.js
- documentation
- split commits for cc-block and commit for elastic (don't forget changelog)
- naming: If we go this way go for override-foobar
- noTitle (boolean: false by default)
Fixes #293, #225, #151
> cc-block: add ribbon and no-head property

- .gitignore
- CHANGELOG.md
- docs/guides/how-to-publish-previews.md
- package-lock.json
- package.json
- tasks/cellar-client.js
- tasks/preview.js
- tasks/publish-cdn.js
> Update AWS S3 client and use it instead of shell exec s3cmd for preview

- CHANGELOG.md
- src/env-var/cc-env-var-form.smart-exposed-config.js
> cc-env-var-form: fix small issues in exposed-config smart definition

- CHANGELOG.md
- docs/translations.example.js
- package-lock.json
- package.json
- rollup/rollup-plugin-deps-manifest.js
- src/addon/cc-elasticsearch-info.js
- src/atoms/cc-button.js
- src/atoms/cc-input-number.js
- src/atoms/cc-input-text.js
- src/env-var/cc-env-var-linked-services.js
- src/invoices/cc-invoice.js
- src/lib/i18n-sanitize.js
- src/lib/i18n-string.js
- src/lib/leaflet-heat.js
- src/lib/product.js
- src/lib/smart-manager.js
- src/lib/zone.js
- src/maps/cc-map.js
- src/mixins/with-resize-observer.js
- src/pricing/cc-pricing-product-consumption.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- src/zones/cc-zone-input.js
- src/zones/cc-zone.js
- stories/lib/i18n-control.js
- stories/lib/make-story.js
- tasks/preview.js
- test/i18n-string.test.js
- web-dev-server.config.js
> Modernize code with safari 14.1 release

- CHANGELOG.md
- docs/cc-example-component.js
- docs/guides/web-components-guidelines.md
- src/invoices/cc-invoice-table.js
- src/overview/cc-header-app.js
- src/overview/cc-tile-instances.js
- src/pricing/cc-pricing-table.js
- src/zones/cc-zone-input.js
Fixes #278 (must merge #314 before)
> refactor: move sub render methods `_renderFoo()` below the main `render()` method

- CHANGELOG.md
- src/addon/cc-header-addon.js
- src/addon/types.d.ts
- src/env-var/cc-env-var-create.js
- src/env-var/cc-env-var-form.js
- src/env-var/cc-env-var-form.smart-config-provider.js
- src/env-var/types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/addon/cc-header-addon.stories.js
- stories/env-var/cc-env-var-form.smart-config-provider.md
- stories/env-var/cc-env-var-form.stories.js
- stories/lib/make-story.js
- web-dev-server.config.js
> Add support for configuration provider to cc-env-var-form (+ bonus)

- CHANGELOG.md
- src/translations/translations.en.js
- src/translations/translations.fr.js
> env-var-*: fix links to the doc

- docs/guides/web-components-guidelines.md
- Added some links to illustrate some of the guidelines,
- Fixed a small typo
> Web Component Guide: small improvements and typo fix

- CHANGELOG.md
- src/lib/product.js
- src/pricing/cc-pricing-product.smart-runtime.js
- stories/pricing/cc-pricing-product.smart-runtime.md
> cc-pricing-product: add details for Heptapod runners

- CHANGELOG.md
- src/tcp-redirections/cc-tcp-redirection-form.js
- src/tcp-redirections/cc-tcp-redirection-form.smart.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/tcp-redirections/cc-tcp-redirection-form.smart.md
- stories/tcp-redirections/cc-tcp-redirection-form.stories.js
> cc-tcp-redirection-form: add smart definition

- CHANGELOG.md
- Jenkinsfile
- docker-runner/Dockerfile
- package.json
> Remove `engines.node` from `package.json` and rely on Volta's versions fields

- CHANGELOG.md
- src/addon/cc-matomo-info.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/addon/cc-matomo-info.stories.js
> cc-matomo-info: init component

- docs/adr/adr-0017-finding-accessible-colors-and-creating-design-tokens.md
- docs/references/resources.reference.md
[Preview link](https://clever-components-preview.cellar-c2.services.clever-cloud.com/colors/init-adr/index.html?path=/story/%F0%9F%93%8C-docs-architecture-decision-records-adr-0017-finding-accessible-colors-and-creating-design-tokens--page)
> ADR: Finding accessible colors and creating Design Tokens

- CHANGELOG.md
- package-lock.json
- package.json
- rollup/rollup-common.js
- src/lib/i18n-sanitize.js
- src/notices/cc-warning-payment.js
- src/notices/types.d.ts
- src/styles/default-theme.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/notices/cc-warning-payment.stories.js
- test/i18n-sanitize.test.js
Fixes #402
Preview : https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-payment-warning/index.html?path=/story/%F0%9F%9B%A0-notices-cc-warning-payment--default-story
> cc-warning-payment: init component

- CHANGELOG.md
- src/homepage/cc-article-card.js
- src/homepage/cc-article-list.js
- src/homepage/cc-article-list.smart.js
- src/homepage/cc-doc-card.js
- src/homepage/cc-doc-list.js
- src/homepage/types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/homepage/cc-doc-card.stories.js
- stories/homepage/cc-doc-list.stories.js
> cc-doc-card: init component

- CHANGELOG.md
- src/lib/xml-parser.js
- test/xml-parser.test.js
> cc-article-list: fix error trigger when xml parsing fails (smart)

- .storybook/preview-head.html
- CHANGELOG.md
- src/env-var/cc-env-var-form.js
- src/env-var/cc-env-var-form.smart-config-provider.js
- src/env-var/cc-env-var-form.smart-env-var-addon.js
- src/env-var/cc-env-var-form.smart-exposed-config.js
- src/env-var/cc-env-var-linked-services.js
- src/env-var/types.d.ts
- src/lib/notifications.js
- src/lib/smart-manager.js
- src/saas/cc-grafana-info.js
- src/saas/cc-grafana-info.smart.js
- src/saas/types.d.ts
- src/tcp-redirections/cc-tcp-redirection-form.js
- src/tcp-redirections/cc-tcp-redirection-form.smart.js
- src/tcp-redirections/cc-tcp-redirection.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/env-var/cc-env-var-form.stories.js
- stories/saas/cc-grafana-info.stories.js
- stories/tcp-redirections/cc-tcp-redirection-form.stories.js
- stories/tcp-redirections/cc-tcp-redirection.stories.js
> Integrate cc-toast into smart components

- cdn-ui/index.html
Fixes #508 
I went for the quick and dirty way.
I feel like the UI is evolving and the code is becoming quite verbose.
Using a declarative pattern, maybe with a very lightweight framework like [petite vue](https://github.com/vuejs/petite-vue) could be great here, even though this UI is WIP ?
> cdn-ui: show style endpoint if relevant

- CHANGELOG.md
- src/maps/cc-map.js
- src/zones/cc-zone-input.js
> cc-map: make dot markers not focusable

- CHANGELOG.md
- src/atoms/cc-toggle.js
> cc-toggle: update host display css property

- docs/guides/how-to-contribute.md
- docs/guides/how-to-release-the-components.md
> docs: move and rename "contributing" and "releases" docs

- CHANGELOG.md
- src/addon/cc-addon-admin.js
> cc-addon-admin: fix skeleton

- docs/guides/how-to-load-components-via-our-smart-cdn.md
> docs: add details about styles in the smart CDN documentation

- docs/adr/adr-0018-how-to-give-feedback-after-a-user-action.md
- docs/adr/adr-0019-how-to-make-toaster-accessible.md
> Add cc-toaster ADR

- web-dev-server.config.js
> Fix the plugin used to inject auth for smart component

- CHANGELOG.md
- demo-smart/index.html
- demo-smart/index.js
- package-lock.json
- package.json
- src/lib/define-smart-component.js
- src/lib/immer.js
- src/stories/lib/story-names.js
- web-dev-server.config.js
* This is still WIP
* Feedbacks are welcomed
* You can rebase your components over this
> Add a new high level / magic API to define a smart component

- CHANGELOG.md
- src/components/cc-input-number/cc-input-number.js
- src/components/cc-input-text/cc-input-text.js
- src/components/cc-select/cc-select.js
- src/components/cc-toggle/cc-toggle.js
> form controls: remove unique IDs and rely on shadow dom isolation

- src/components/cc-button/cc-button.js
> feat(cc-button): use aria-disabled attribute instead of disabled

- CHANGELOG.md
- src/components/cc-button/cc-button.js
- src/components/cc-button/cc-button.stories.js
> feat(cc-button): add an accessibleName prop

- CHANGELOG.md
- src/components/cc-stretch/cc-stretch.js
- src/components/cc-stretch/cc-stretch.stories.js
Fixes #592 
[cc-stretch](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-stretch/index.html?path=/story/%F0%9F%A7%AC-atoms-cc-stretch--default-story)
> feat(cc-stretch): init new component

- src/styles/default-theme.css
Fixes #594 
2 approvals should be enough for this one :wink:
> docs(default-theme): explicit how custom properties are to be sorted

- .commitlintrc
- .githooks/commit-msg
- .github/workflows/release.yml
- CONTRIBUTING.md
- docs/guides/how-to-release-the-components.md
- package-lock.json
- package.json
Fixes: #330
**We must merge this just after a manual old-school release**
> ci(release): conventional commit

- docs/guides/how-to-release-the-components.md
> docs: fix the npm package publish command

- src/components/cc-notice/cc-notice.js
- src/components/cc-notice/cc-notice.stories.js
- src/components/cc-notice/cc-notice.test.js
- src/components/cc-notice/cc-notice.types.d.ts
- src/components/cc-warning-payment/cc-warning-payment.js
- src/styles/default-theme.css
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #343 
Fixes #634
preview here: https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-notice/index.html?path=%2Fstory%2F%F0%9F%A7%AC-atoms-cc-notice--default-story
> feat(cc-notice): init new component

- src/components/cc-badge/cc-badge.js
Fixes #654
2 reviews should be enough for this one :wink:
> fix(cc-badge): override border in skeleton mode

- web-test-runner.config.js
Fixes #653
* Check the code.
* As long as the CI task is still running fine we're all good.
* 2 reviewers should be enough
> chore(web-test-runner): increase timeout to 10s

- docs/adr/adr-0023-adding-stylelint.md
Fixes #122 
While I haven't checked yet for every spelling and errors that might be present in the doc,  I wanted to have your feedback first on the content.
So let me know if you think some information are missing or if there are things you don't understand. :slightly_smiling_face: :pray:
> docs: add new Stylelint ADR

- .github/workflows/test-and-build.yml
> ci(test-and-build): add some missing tasks and reorganize tasks

- src/components/cc-overview/cc-overview.stories.js
> feat(cc-overview): add cc-tile-metrics to the app-mode story

- src/components/cc-zone/cc-zone.js
> feat(cc-zone): add infra if any to the getText() static method

- .github/workflows/preview.yml
- package.json
- tasks/preview.js
> ci: automate preview creation on PR submission

- src/components/cc-env-var-form/cc-env-var-form.js
> fix(cc-env-var-form): fix textarea cropped focus outline

- cem/support-typedef-jsdoc.js
> fix: issue in Custom Element Manifest generation when detecting @typedef imports

- src/translations/translations.en.js
> fix(cc-email-list): fix sample domain name

- src/components/cc-block/cc-block.js
> fix(cc-block): fix close button title

- docs/adr/adr-0002-how-we-do-i18n.md
- docs/guides/how-to-translate-and-localize.md
> docs: fix translation examples

- docs/guides/how-to-use-the-components-theme.md
> docs: fix default-theme usage guides

- package-lock.json
- package.json
- src/pricing/cc-pricing-header.js
- src/pricing/cc-pricing-table.js
- stories/pricing/cc-pricing-product.stories.js
- stories/pricing/cc-pricing-table.stories.js
Fixes #781 
Fixes #787
- Updates the shoelace dependency to fix the issue with `cc-pricing-header` and Chrome. 
- Modifies `cc-pricing-table` to stop filtering features that have no translations and display the raw code as the feature name within the table headers.
Bear in mind that these modifications are quick fixes:
- Review both commits.
- Check out these three stories:
- [cc-pricing-header](https://clever-components-preview.cellar-c2.services.clever-cloud.com/7.13.0/index.html?path=/story/%F0%9F%9B%A0-pricing-cc-pricing-header--default-story) => play with the select. The design should be the same as the pricing page of the website + everything should be working correctly (check the website on FF and check the story with Chrome).
- [Product with custom …
> legacy pricing components (v7.12.0):  fix shoelace and allow custom product features

- src/components/cc-addon-elasticsearch-options/cc-addon-elasticsearch-options.stories.js
- src/components/cc-addon-jenkins-options/cc-addon-jenkins-options.stories.js
- src/components/cc-addon-mongodb-options/cc-addon-mongodb-options.stories.js
- src/components/cc-addon-mysql-options/cc-addon-mysql-options.stories.js
- src/components/cc-addon-postgresql-options/cc-addon-postgresql-options.stories.js
- src/components/cc-addon-redis-options/cc-addon-redis-options.stories.js
- src/components/common.types.d.ts
- src/templates/cc-addon-encryption-at-rest-option/cc-addon-encryption-at-rest-option.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
> feat(cc-addon-encryption-at-rest-option): Remove pricing notice on addon encryption at rest option

- docs/adr/adr-0022-new-icon-system.md
Fixes #767 
:sweat_smile: 
A simple documentation update that should be straight-forward to review.
> docs(adr): update Remix Icon project activity

- docs/guides/breaking-change-policy.md
> docs(breaking-changes): add breaking change policy

- cem/support-typedef-jsdoc-utils.js
- cem/support-typedef-jsdoc.js
- cem/test/fixtures/cc-test-component.js
- cem/test/fixtures/cc-test-component.types.d.ts
- cem/test/support-typedef-jsdoc-utils.test.js
- src/components/cc-addon-jenkins-options/cc-addon-jenkins-options.js
- src/components/cc-addon-mysql-options/cc-addon-mysql-options.js
- src/components/cc-addon-redis-options/cc-addon-redis-options.js
- src/components/cc-env-var-create/cc-env-var-create.js
- src/components/cc-env-var-input/cc-env-var-input.js
- src/components/cc-env-var-input/cc-env-var-input.types.d.ts
- src/components/cc-map/cc-map.js
- src/components/cc-orga-member-card/cc-orga-member-card.js
- src/components/cc-orga-member-list/cc-orga-member-list.js
- src/components/cc-orga-member-list/cc-orga-member-list.types.d.ts
- src/components/cc-pricing-product-consumption/cc-pricing-product-consumption.js
- src/components/cc-pricing-product/cc-pricing-product.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.types.d.ts
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.js
- src/components/cc-tcp-redirection/cc-tcp-redirection.js
- src/components/cc-tcp-redirection/cc-tcp-redirection.types.d.ts
- src/components/cc-toast/cc-toast.types.d.ts
- src/components/cc-toaster/cc-toaster.js
- src/components/common.types.d.ts
- tasks/check-type-imports.js
In this PR, you'll find several commits:
Fixes #836
Fixes #837
Fixes #838
Fixes #839 
Fixes #840
Fixes #841
> Enhance doc and types support

- src/components/cc-select/cc-select.js
- src/components/cc-toggle/cc-toggle.js
> fix(cc-toggle / cc-select): add and reflect name attributes

- .storybook/manager.js
Fixes #850
- check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/storybook/fix-brand-logo/index.html), if the logo on the top left corner is visible, we're good.
- check the same thing in local.
> chore(storybook): update the `brandImage` url

- src/components/cc-input-text/cc-input-text.js
> refactor(cc-input-text): use arrayEquals from utils

- src/lib/xml-parser.js
- test/xml-file-test.xml
- test/xml-parser.test.js
Fixes #867 
* Check the UI
* Go to `https://clever-components-preview.cellar-c2.services.clever-cloud.com/fix-article-smart/index.html?path=%2Fstory%2F%F0%9F%9B%A0-homepage-cc-article-list-%F0%9F%92%A1-smart--page` 
* Check that the component load correctly
* Check both english and french
* (With the new RSS the description is longer, I can't really do much about that sadly)
* Review the code except the sandbox commit. I thought we could use it but the smart page can act as a sandbox for us :wink:
> cc-article-list: fix XML parser

- .github/workflows/release.yml
> ci: add emoji in front of CHANGELOG sections

- .github/workflows/preview.yml
- .github/workflows/publish.yml
- .github/workflows/test-and-build.yml
> ci: cache npm dependencies

- src/components/cc-header-addon/cc-header-addon.js
- src/components/cc-header-orga/cc-header-orga.js
- src/components/cc-img/cc-img.js
- src/components/cc-img/cc-img.stories.js
- src/components/cc-zone/cc-zone.js
> fix(cc-img): populate alt value

- src/components/cc-button/cc-button.js
- src/components/cc-popover/cc-popover.js
- src/components/cc-popover/cc-popover.stories.js
- src/components/cc-popover/cc-popover.test.js
- src/components/cc-popover/cc-popover.types.d.ts
- src/lib/events.js
> feat(cc-popover): init component

- src/components/cc-logs/cc-logs.js
Fixes #904
1 reviewer is more than enough for this one.
> docs(cc-logs): set the correct typedef for `TimeZone`

- package-lock.json
- package.json
- test/helpers/accessibility.js
Fixes #808
This PR replaces our code with the `@lit-labs/virtualizer` utility.
> test: use resize-observer-errors utility from `@lit-labs/virtualizer`

- demo-smart/index.html
- src/components/cc-tile-status-codes/cc-tile-status-codes.js
- src/components/cc-tile-status-codes/cc-tile-status-codes.smart.js
- src/components/cc-tile-status-codes/cc-tile-status-codes.stories.js
- src/components/cc-tile-status-codes/cc-tile-status-codes.types.d.ts
- web-dev-server.config.js
> refactor(cc-tile-status-codes)!: migrate to the new smart component design

- demo-smart/index.html
- src/components/cc-jenkins-info/cc-jenkins-info.js
- src/components/cc-jenkins-info/cc-jenkins-info.smart.js
- src/components/cc-jenkins-info/cc-jenkins-info.stories.js
- src/components/cc-jenkins-info/cc-jenkins-info.types.d.ts
> refactor(cc-jenkins-info)!: migrate to the new smart component design

- demo-smart/index.html
- src/components/cc-grafana-info/cc-grafana-info.js
- src/components/cc-grafana-info/cc-grafana-info.smart.js
- src/components/cc-grafana-info/cc-grafana-info.stories.js
- src/components/cc-grafana-info/cc-grafana-info.types.d.ts
> refactor(cc-grafana-info)!: migrate to the new smart component design

- src/components/cc-tile-deployments/cc-tile-deployments.js
- src/components/cc-tile-deployments/cc-tile-deployments.stories.js
- src/components/cc-tile-deployments/cc-tile-deployments.types.d.ts
Fixes #942
* rework the properties to use our new way of implementing component states (this is a breaking change)
* remove confusion on Deployment type
> refactor(cc-tile-deployments)!: rework properties to make impossible state impossible

- demo-smart/index.html
- src/components/cc-invoice/cc-invoice.js
- src/components/cc-invoice/cc-invoice.smart.js
- src/components/cc-invoice/cc-invoice.stories.js
- src/components/cc-invoice/cc-invoice.types.d.ts
> refactor(cc-invoice)!: migrate to the new smart component design

- src/components/cc-tile-instances/cc-tile-instances.js
- src/components/cc-tile-instances/cc-tile-instances.stories.js
- src/components/cc-tile-instances/cc-tile-instances.types.d.ts
- src/components/common.types.d.ts
Fixes #927
Also fixes a part of #917.
* rework the properties to use our new way of implementing component states (this is a breaking change)
* remove confusion on Instance type (see #917)
> refactor(cc-tile-instances)!: rework properties to make impossible state impossible

- demo-smart/index.html
- src/components/cc-invoice-list/cc-invoice-list.js
- src/components/cc-invoice-list/cc-invoice-list.smart.js
- src/components/cc-invoice-list/cc-invoice-list.stories.js
- src/components/cc-invoice-list/cc-invoice-list.types.d.ts
> refactor(cc-invoice-list)!: migrate to the new smart component design

- src/components/cc-loader/cc-loader.js
- src/components/cc-loader/cc-loader.stories.js
- src/components/cc-logs-instances/cc-logs-instances.js
- src/components/cc-logs-instances/cc-logs-instances.stories.js
- src/components/cc-logs-instances/cc-logs-instances.test.js
- src/components/cc-logs-instances/cc-logs-instances.types.d.ts
- src/lib/utils.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- test/utils.test.js
> feat(cc-logs-instances) init Component

- src/lib/send-to-api.js
> feat: add error event from `sendToApi` calls

- src/lib/define-smart-component.js
> fix(smart-component): protect from abortController nullity when smart component is disconnected

- src/components/cc-product-list/cc-product-list.js
- src/components/cc-product-list/cc-product-list.stories.js
- src/components/cc-product-list/cc-product-list.test.js
- src/components/cc-product-list/cc-product-list.types.d.ts
- src/components/cc-product-list/products-controller.js
- src/components/cc-product-list/products-controller.test.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #892
* This PR init a component that handles the step 1 of the future creation tunnel.
* Check the overall design
*  Check the code
> feat(cc-product-list): init component

- src/components/cc-logsmap/cc-logsmap.js
- src/components/cc-logsmap/cc-logsmap.stories.js
> feat(cc-logsmap): allow the configuration of modes (availability and order)

- src/components/cc-addon-credentials/cc-addon-credentials.stories.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
I've updated texts, let me know if you need/want me to change more references to Materia KV
> fix: update Materia branding

- src/components/cc-article-card/cc-article-card.js
- src/components/cc-article-card/cc-article-card.stories.js
- src/components/cc-article-card/cc-article-card.types.d.ts
- src/components/cc-article-list/cc-article-list.js
- src/components/cc-article-list/cc-article-list.smart.js
- src/components/cc-article-list/cc-article-list.stories.js
- src/components/cc-article-list/cc-article-list.types.d.ts
- Refactors the `cc-article-list` & `cc-article-card` components to implement our new state structure,
- Implements TypeChecking within the `cc-article-list` & `cc-article-card` components and their stories.
- Compare the [cc-article-card prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-homepage-cc-article-card--default-story) to the [preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-article-list/state-migration/index.html?path=/story/%F0%9F%9B%A0-homepage-cc-article-card--default-story), …
> refactor(cc-article-components)!: rework properties to avoid impossible states

- sandbox/cc-logs-application-view/cc-logs-application-view-sandbox.js
- src/components/cc-logs-application-view/cc-logs-application-view.js
- src/components/cc-logs-application-view/cc-logs-application-view.smart.js
- src/components/cc-logs-application-view/cc-logs-application-view.types.d.ts
- src/components/cc-logs-application-view/date-range-selection.js
Fixes #1074
Fixes #1075
- You should see a new event when changing the date range
- Use the sandbox with the dateRangeSelection selector
> feat(cc-logs-application-view): allow store and restore of the selected date range

- .storybook/main.js
- docs/contributing/tasks.md
> docs: add tasks documentation

- src/components/cc-kv-console/cc-kv-console.stories.js
- src/components/cc-kv-explorer/cc-kv-explorer.stories.js
- src/components/cc-kv-hash-explorer/cc-kv-hash-explorer.js
- src/components/cc-kv-hash-explorer/cc-kv-hash-explorer.stories.js
- src/components/cc-kv-hash-input/cc-kv-hash-input.stories.js
- src/components/cc-kv-list-explorer/cc-kv-list-explorer.js
- src/components/cc-kv-list-explorer/cc-kv-list-explorer.stories.js
- src/components/cc-kv-list-input/cc-kv-list-input.stories.js
- src/components/cc-kv-set-explorer/cc-kv-set-explorer.js
- src/components/cc-kv-set-explorer/cc-kv-set-explorer.stories.js
- src/components/cc-kv-string-editor/cc-kv-string-editor.stories.js
> fix(cc-kv-explorer): wrong gap between buttons in hash, list and set explorers

- docs/contributing/resources.md
- Adds new items to project resources to read.
No review required
> docs(resources): add article about JSDoc and ARIA Design Patterns

- src/components/cc-kv-explorer/cc-kv-explorer.js
- src/components/cc-kv-explorer/cc-kv-explorer.smart.js
- src/components/cc-kv-explorer/cc-kv-explorer.stories.js
- src/components/cc-kv-explorer/cc-kv-explorer.types.d.ts
- src/components/cc-kv-explorer/kv-key-hash-ctrl.js
- src/components/cc-kv-explorer/kv-key-set-ctrl.js
- src/components/cc-kv-explorer/kv-keys-ctrl.js
- src/components/cc-kv-hash-explorer/cc-kv-hash-explorer.js
- src/components/cc-kv-hash-input/cc-kv-hash-input.js
- src/components/cc-kv-list-explorer/cc-kv-list-explorer.js
- src/components/cc-kv-list-input/cc-kv-list-input.js
- src/components/cc-kv-set-explorer/cc-kv-set-explorer.js
- src/components/cc-kv-string-editor/cc-kv-string-editor.js
- src/components/cc-kv-terminal/cc-kv-terminal.js
- src/components/cc-kv-terminal/cc-kv-terminal.stories.js
- src/components/cc-kv-terminal/cc-kv-terminal.test.js
- src/components/cc-kv-terminal/cc-kv-terminal.types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
This PR handles various feedback that have been made during the last 2 weeks.
There is nothing really breaking, and this is mostly about refactoring things.
Each feedback has its dedicated commit.
* Just check the code
> cc-kv-explorer: various feedback

- src/components/cc-order-summary/cc-order-summary.js
- src/components/cc-order-summary/cc-order-summary.stories.js
- src/components/cc-order-summary/cc-order-summary.test.js
- src/components/cc-order-summary/cc-order-summary.types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1304 
Quite a simple review
- check the code
- check the preview
> feat(creation-tunnel): init order summary component

- src/translations/translations.fr.js
Fixes #872 
* This PR fixes the loading error translation that was in english in the french translations
* Check the translations
* Check the preview
* Feel free to suggest another translation
* One reviewer should be enough
> fix: fix french Matomo loading error translation

- docs/adr/adr-0028-making-our-component-apis-more-robust.md
- Adds an ADR about Component states.
> Docs: Add ADR about Component States

- package.json
Adds check of the code format during build process
> build: add code format check

- docs/contributing/forms.md
- Adds some docs about forms in clever components
This may not be perfect (AI generated and then reworked) but it should be better than nothing and cover most cases :+1: 
> [!NOTE]
> We'll need another separate doc about how to build a form control element with the `CcFormControlElement` abstract class
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/docs/contributing-forms-guidelines/index.html?path=/docs/%F0%9F%91%8B-contributing-forms-guidelines--docs),
- 3 reviewers should be enough but I need @pdesoyres-cc specifically :wink:
> docs(contributing/forms): init

- docs/getting-started/smart-component.md
- Adds more details about how to use / consume smart components
This may not be perfect (AI generated and then reworked) but it should be better than nothing and cover most cases :+1: 
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/docs/getting-started-smart-components/index.html?path=/docs/%F0%9F%8F%A1-getting-started-smart-components--docs),
- 3 reviewers should be enough.
> docs(getting-started/smart-component): explain how to consume smart components

- docs/contributing/smart-component.md
- Adds some docs about forms in smart components (from a contributor's Point Of View)
This may not be perfect (AI generated and then reworked) but it should be better than nothing and cover most cases :+1: 
- Check the preview,
- 3 reviewers should be enough.
> docs(contributing/smart-component): init

- src/components/cc-logs-date-range-selector/cc-logs-date-range-selector.js
This PR fixes #1356
* Just check that the scenario described in the issue is fixed
* One reviewer should be enough
> fix(cc-logs-date-range-selector): fix `since` and `until` dates edition

- docs/getting-started/design-tokens.md
- src/components/cc-input-date/cc-input-date.js
- src/components/cc-input-date/cc-input-date.stories.js
- src/components/cc-input-number/cc-input-number.js
- src/components/cc-input-number/cc-input-number.stories.js
- src/components/cc-input-text/cc-input-text.js
- src/components/cc-input-text/cc-input-text.stories.js
- src/components/cc-plan-picker/cc-plan-picker.js
- src/components/cc-select/cc-select.js
- src/components/cc-select/cc-select.stories.js
- src/components/cc-toggle/cc-toggle.js
- src/components/cc-toggle/cc-toggle.stories.js
- src/components/cc-zone-picker/cc-zone-picker.js
- src/styles/default-theme.css
Fixes #1362
Add some custom properties, most of them being among several components.
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/form-controls-gap-uniformisation/index.html)
- look for visual regression
- Check the code
- don't hesitate to challenge the variable name
- Two reviewers should do as it's pretty straightforward
> Standardize some style usage related to form

- package-lock.json
- package.json
- src/components/cc-addon-linked-apps/cc-addon-linked-apps.smart.js
Closes #1380.
- one commit to bump `clever-client.js` dependency
- one commit to update the `cc-addon-linked-apps` smart
- check the code
- checkout the branch and check with the smart demo that the component properly pass the `ownerId` query param to the `/v4/products/zones` endpoint
One person should be enough.
> cc-addon-linked-apps: update zones API call in smart

- src/components/cc-block-details/cc-block-details.js
- src/components/cc-block-details/cc-block-details.stories.js
- src/styles/cli-commands.js
- Fixes the cc-block-details component by correcting the documentation and style.
- Check the default component story within the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/fix/cc-block-details/index.html?path=/docs/%F0%9F%A7%AC-molecules-cc-block-details--docs)
> fix(cc-block-details): fix folder name and update style

- src/components/cc-token-oauth-list/cc-token-oauth-list.js
- src/components/cc-token-oauth-list/cc-token-oauth-list.stories.js
Fixes #1439
- Fixes cases where the logo of the consumer is cropped (see screenshot below)
- Check the commit, 
- Check the preview.
> fix(cc-token-oauth-list): prevent images from being cropped

- demo-smart/index.html
- src/components/cc-addon-backups/cc-addon-backups.smart.js
- src/components/cc-addon-backups/cc-addon-backups.smart.md
- Adds a smart part to the component `cc-addon-backups`
- Check the demo-smart page on the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/feat/cc-addon-backups.smart/index.html?path=/docs/%F0%9F%9B%A0-addon-cc-addon-backups-%F0%9F%92%A1-smart--docs)
> feat(cc-addon-backups): add smart part

- src/components/cc-env-var-form/cc-env-var-form.smart-env-var-app.js
- src/components/cc-env-var-form/cc-env-var-form.smart-env-var-app.md
Fixes #1513 
- Changes the smart part to display the restart button only if the app already been deployed
- Check the commit
> fix(cc-env-var-form): display restart button only if app already been deployed

- src/components/cc-web-features-tracker/web-features.json
- Adds `container-queries` to the browser support contributing docs.
- No reviews necessary
> docs(contributing/browser-support): add `container-queries`

- src/components/cc-addon-header/cc-addon-header.smart-keycloak.js
- src/components/cc-addon-info/cc-addon-info.smart-keycloak.md
- Removes useless `const` in header smart,
- Improves smart info doc.
- Check the code.
1 reviewer should be enough.
> refactor(cc-addon-*): small refactoring on Keycloak add-on
