CleverCloud/clever-components

- components/atoms/cc-button.js
- components/atoms/cc-expand.js
- components/atoms/cc-input-text.js
- components/info-tiles/cc-info-instances.js
This is sad, but Safari does not support `element.animate()`.
In most cases this is ok not to have the animation (cc-expand, cc-info-instances).
In the case of the delay animation of a `<cc-button>`, we really need it.
We went for a `<progress>` element in the DOM and we animated its background.
> cc-button: fix Safari element.animate()

- components/lib/i18n-sanitize.js
- components/translations/translations.fr.js
Hi!
The following command  reported errors:
```sh
$ npm run lint
> @clevercloud/components@1.3.0 lint /home/foo/bar/clever-components
> eslint components stories tasks
/home/foo/bar/clever-components/components/lib/i18n-sanitize.js
7:7  error  'globalThis' is not defined  no-undef
/home/foo/bar/clever-components/components/translations/translations.fr.js
6:8   error  '/home/foo/bar/clever-components/components/lib/i18n-date.js' imported multiple times  import/no-duplicates
8:39  error  '/home/foo/bar/clever-components/components/lib/i18n-date.js' imported multiple times  import/no-duplicates
✖ 3 problems (3 errors, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
```
Then I used `npm run lint:fix` to automatically fixed the `translations.fr.js` file.
I've …
> Fix ESLint errors

- components/env-var/env-var-editor-expert.js
- package-lock.json
- package.json
The way env vars were parsed and serialized between simple and expert mode had a few glitches. Look at https://github.com/CleverCloud/clever-client.js/pull/18 for more details.
> Fix env var parsing

- src/overview/cc-header-orga.js
I missed this when doing the `<cc-flex-gap>` refactor.
> cc-header-orga: fix vertical alignment

- src/tcp-redirections/cc-tcp-redirection-form.js
- stories/tcp-redirections/cc-tcp-redirection-form.stories.js
Do not show description if context != user, this will be used by Clever Cloud Admin interface.
> cc-tcp-redirection-form: add context property

- src/addon/cc-addon-option.js
This fixes some missing styles (toggle color and border radius) for the `<cc-addon-option>` component
> cc-addon-option: fix styling

- stories/lib/make-story.js
Error:
```
/home/arnaud/Dev/clevercloud/clever-components/stories/lib/make-story.js
77:51  error  Unnecessary parentheses around expression
no-extra-parens
✖ 1 problem (1 error, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
```
> make-story: fix lint error preventing prepack to work

- CHANGELOG.md
- src/addon/cc-addon-mongodb-options.js
- src/addon/cc-addon-mysql-options.js
- src/addon/cc-addon-postgresql-options.js
- src/templates/cc-addon-encryption-at-rest-option.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
There is now a dedicated documentation for this feature instead of
having it in each of the add-ons.
I guess this is a breaking change.
> Encryption at rest: update documentation link

- stories/molecules/cc-block-section.stories.js
Looks like there is a typo.
Replaced all `Adress` by `Address`.
> cc-block-section: fix typo

- CHANGELOG.md
- src/atoms/cc-toggle.js
> cc-toggle: remove padding when legend is empty

- CHANGELOG.md
- src/atoms/cc-beta.js
- src/atoms/cc-button.js
- src/atoms/cc-img.js
- src/atoms/cc-input-number.js
- src/atoms/cc-input-text.js
- src/atoms/cc-loader.js
- src/atoms/cc-toggle.js
- src/overview/cc-tile-requests.js
- src/overview/cc-tile-status-codes.js
* This patch replaces all `rem` with `em` in all atoms components
* This also includes a modification on some tile components
* See https://github.com/CleverCloud/clever-components/issues/126#issuecomment-797600763 for context
NOTE: Some dimensions are a bit different
> atoms: replace rem with em

- CHANGELOG.md
- package-lock.json
- package.json
- src/addon/cc-jenkins-info.js
- src/addon/cc-jenkins-info.smart.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/addon/cc-jenkins-info.smart.md
- stories/addon/cc-jenkins-info.stories.js
This PR adds a new component, named `<cc-jenkins-info>` with its smart definition.
This component will be used to display some information about a Jenkins add-on like the documentation link, the link to the Jenkins UI and some information about available updates.
This PR also bumps the `@clevercloud/client` dependency to `^7.6.0` as we need a new endpoint released in that version for the smart component.
Fix #272
> Add <cc-jenkins-info> component

- CHANGELOG.md
- docs/cc-example-component.js
- src/invoices/cc-invoice-table.js
- src/overview/cc-overview.js
- src/pricing/cc-pricing-estimation.js
- src/pricing/cc-pricing-product-consumption.js
- src/pricing/cc-pricing-table.js
Fixes #282 (must merge #315 before)
> refactor: use code folding regions in CSS (especially for responsive with COMMON/BIG/SMALL modes)

- CHANGELOG.md
- src/atoms/cc-input-number.js
Probably due to the types introduction min and max were set to null by default in the constructor which caused the condition to check if the controls should be disabled when checking min and max broke because it wasn't checking if they were null (which means we don't have a min or max)
> cc-input-number: fix controls mode not working properly

- CHANGELOG.md
- src/atoms/cc-input-number.js
- src/atoms/cc-input-text.js
- src/atoms/cc-select.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- stories/atoms/cc-input-number.stories.js
- stories/atoms/cc-input-text.stories.js
- stories/atoms/cc-select.stories.js
* Add help text and error message support as well as their related stories.
* Remove label stories.
* Add label inside all stories.
* Add help text support as well as its related story.
* Tweaked label CSS to make it simpler.
- Code format: hope prettier and I did not mess things up @hsablonniere :angel: 
- [Preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-input/required-and-help-text/index.html)
TODO before merging:
> Form controls: Help texts and error messages

- CHANGELOG.md
- src/atoms/cc-input-number.js
- src/atoms/cc-input-text.js
- src/atoms/cc-select.js
- src/atoms/cc-toggle.js
- src/styles/default-theme.js
- stories/atoms/all-form-controls.js
Fixes #446 
- Added a new section in the `all-form-controls` story to showcase all form controls horizontally aligned with help messages below each form control.
- Specified line-height on the `<label>` (`cc-input-*` + `cc-select`)/ `<legend>` (`cc-toggle`) element of all the form controls.
- Aligned all the form controls from top (`align-items: start`).
- Added a margin variable in `defaultThemeStyles` to be used as `margin-top` value on a `cc-button` so that it is aligned with the rest of form controls (specifies an offset equal to `label` height (line-height + padding = `1.6em` )
- Added small paragraph to try and explain all of this :sweat_smile:.
> all-form-controls: add support and story for horizontal form layout

- docs/guides/accessibility-reminders.md
This documentation provides reminders for accessibility rules we should enforce through all the components.
These rules are solutions for common issues that we face.
At the moment, there is only one rule about providing accessible explicit names for links.
The documentation will be updated every time we face a new issue that is not specific to only one component.
> Documentation about common accessibility rules

- CHANGELOG.md
- src/atoms/cc-button.js
- stories/atoms/cc-button.stories.js
Here are some design proposal for the `cc-button` waiting mode in circle state :
- [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-button-circle-loader/index.html?path=/story/%F0%9F%A7%AC-atoms-cc-button--circle-waiting)
- fixes #449 
I tried to present multiple combinations in the story, varying on:
- mode (simple, primary, success, etc.)
- icon size
- ring radius
- opacity (global, icon only, none)
- icon transparent or not
Note: feel free to zoom with the related action on the top toolbar.
Just vote for your overall favorite option! (and do not look at the code yet :smile:)
> cc-button: update waiting loader animation in circle state

- CHANGELOG.md
- src/addon/cc-header-addon.js
- src/assets/error.svg
- src/atoms/cc-badge.js
- src/atoms/types.d.ts
- src/notices/cc-warning-payment.js
- src/overview/cc-header-app.js
- src/overview/cc-header-orga.js
- src/styles/default-theme.js
- src/tcp-redirections/cc-tcp-redirection-form.js
- stories/atoms/cc-badge.stories.js
:wave: Hey there ! 
Fixes #462 
The [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-badge/index.html?path=/story/%F0%9F%A7%AC-atoms-cc-badge--dimmed) has been updated following your feedback (thanks again :heart:)
Padding and font-size have been reduced just a little bit. The size is very close to what what we use in `<cc-orga-member-card>` and `<cc-email-list>` and it matches what was already used in `<cc-header-orga>`.
* [`<cc-badge>` stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-badge/index.html?path=/story/%F0%9F%A7%AC-atoms-cc-badge--dimmed),
* [`<cc-header-orga>` stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-badge/index.html?path=/story/%F0%9F%9B%A0-overview-cc-header-orga--defa …
> cc-badge: init component

- CHANGELOG.md
- src/atoms/cc-input-number.js
- src/atoms/cc-input-text.js
- src/atoms/cc-select.js
- src/atoms/cc-toggle.js
- src/invoices/cc-invoice-list.js
- stories/atoms/cc-input-number.stories.js
- stories/atoms/cc-input-text.stories.js
- stories/atoms/cc-select.stories.js
- stories/atoms/cc-toggle.stories.js
Fixes #451.
:wave: Hey there !
I updated the [Preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/form-fields/inline-label/index.html).
Most of the changes are related to `<cc-toggle>` and `<cc-invoice-list>` :+1: 
- "inline" stories (+ inline required and inline with error / help messages) for these components:
- `<cc-input-number>`,
- `<cc-input-text>`,
- `<cc-select>`,
- `<cc-toggle>` (only one inline story since `cc-toggle` does not support required and help messages (and I'm not sure it should but it's another subject).
- `<cc-invoice-list>` stories (both desktop and mobile), the "year" filter is now "inlined".
Every commit.
> cc-input-, cc-select, cc-toggle: support inline layout (label next to form field)

- src/overview/cc-header-orga.js
Because the cc-badge uses a box-shadow as a "border", when overriding the box-shadow to create a focus ring in the `<cc-header-orga>`, the "border" disappeared like this:
With this fix, we have the focus ring AND the "border":
> cc-header-orga: fix cc-badge usage with focus style

- docs/guides/accessibility-reminders.md
Added 2 new sections to the a11y docs:
- decorative svgs
- title attribute usage
> Docs A11Y: decorative svg and title attribute usage

- CHANGELOG.md
- src/atoms/cc-input-text.js
> cc-input-text with tags: set default font back to `--cc-ff-monospace`

- CHANGELOG.md
- tasks/check-i18n.js
Fixes #91.
- Remove log of each single file scanned.
- Display amount of file scanned, key missing and key unused.
- Display success message when no key are missing or being unused.
- Regroup languages for each key missing or unused.
- Add some colors and emojis.
- Display task execution duration.
> task: improve i18n check display

- CHANGELOG.md
- src/components/cc-env-var-form/cc-env-var-form.js
Fix #543.
Initial code was using array spreading on a variable (when the user toggles to JSON mode). But this variable can be `null` when the component is in skeleton state.
The fix is checking the variable value and spreading only if it is not null.
> cc-env-var-form: fix toggling to JSON mode while in skeleton state

- docs/adr/adr-0021-from-rem-to-em.md
Fixes #542 
About the context section
I did not want to go into all the details about the difference between Zoom and Font resizing but it felt like it was necessary to write down why we had chosen to use relative units and why `rem` specifically.
Is it too much ? Or not enough ? :sweat_smile: 
As always, looking forward to your feedback :wink:
> ADR: Switching from rem to em units

- CHANGELOG.md
- src/components/cc-action-dispatcher/cc-action-dispatcher.js
- src/components/cc-action-dispatcher/cc-action-dispatcher.stories.js
- src/components/cc-action-dispatcher/cc-action-dispatcher.types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #353 
We want to create a web component that sends a "ping all VMs" message to the CC Admin (in fact, ping the action dispatcher instances, there is one per VM). And display the results: how many VMs were pinged, how many answered with "pong", and the ids of the unresponsive action dispatcher instances.
> cc-action-dispatcher, ping all VMs

- CHANGELOG.md
- src/components/cc-badge/cc-badge.js
- src/components/cc-badge/cc-badge.stories.js
Fixes #521 
Visually there is no difference but I added the preview so that you can compare the DOM which differs from the first implementation: https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-badge-skeleton-impl-2/index.html
This implementation breaks the initial philosophy which is based on the `:host` CSS selector to apply styles. Instead, it adds a root `<div>` tag which receives all the CSS classes needed to apply style for the different modes (intent, weight, ...)
I add the modify all the CSS selectors to be based on classes instead of `host:`.
Adding the skeleton mode is straightforward as it uses the `skeleton.js` in the same way as usual.
> cc-badge: add skeleton mode / impl 2

- CHANGELOG.md
- src/components/cc-select/cc-select.js
- src/components/cc-select/cc-select.stories.js
Fixes #514 
The `cc-select` component was relying on the `selected` attribute instead of the value property.
```js
<option
value=${option.value}
?selected=${option.value === this.value}
>
${option.label}
</option>
```
This led to inconsistent renders. 
The `value` of the component and the visually selected option could end up completely disconnected when trying to set the `value` of the component from outside (changing the value programmatically with no user action).
Also, the `selected` attribute is supposed to only be used to set the initial / default value of the `<select>` element.
It is not supposed to reflect the `<select>` value as explained in the [MDN Docs about the select element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attr-selected).
It behaves just …
> cc-select: use value property instead of selected attribute

- CHANGELOG.md
- src/components/cc-addon-linked-apps/cc-addon-linked-apps.smart.js
- src/components/cc-article-list/cc-article-list.smart.js
- src/components/cc-env-var-form/cc-env-var-form.smart-config-provider.js
- src/components/cc-env-var-form/cc-env-var-form.smart-env-var-addon.js
- src/components/cc-env-var-form/cc-env-var-form.smart-exposed-config.js
- src/components/cc-grafana-info/cc-grafana-info.smart.js
- src/components/cc-invoice-list/cc-invoice-list.smart.js
- src/components/cc-invoice/cc-invoice.smart.js
- src/components/cc-jenkins-info/cc-jenkins-info.smart.js
- src/components/cc-pricing-page/cc-pricing-page.smart.js
- src/components/cc-pricing-product-consumption/cc-pricing-product-consumption.smart.js
- src/components/cc-pricing-product/cc-pricing-product.smart-addon.js
- src/components/cc-pricing-product/cc-pricing-product.smart-runtime.js
- src/components/cc-smart-container/cc-smart-container.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.smart.js
- src/components/cc-tile-status-codes/cc-tile-status-codes.smart.js
- src/lib/define-smart-component-with-observables.js
- src/lib/smart-manager.js
- test/smart/smart-manager.suite.js
Hey folks,
We're going to deprecate (and then remove) the current `defineComponent` function from the smart manager which is based on Observables and RxJS.
In this PR:
* add some comments (just the first step)
* rollback the `defineComponent` function to the previous low level API with 3 callbacks `onConnect`, `onContextUpdate` and `onDisconnect`
* reimplement the current `defineComponent` function (based on just one `onConnect` callback and a `context$` observable) with the "new" low level API in a different file `smart-manager-observables.js`
* cleanup the test suite
* BTW the test suite was kinda still testing the low level API with a dirty hack, it's better now
Next steps
* Define a new high level API (not based on observables) with a bit more magic
* Write some more comments, JSDoc …
> refactor: rollback the smart-manager to the old low level API and move the observable API to a different module

- .storybook/preview.js
- CHANGELOG.md
- package-lock.json
- package.json
- src/controllers/lost-focus-controller.js
- src/controllers/lost-focus-controller.md
- src/controllers/lost-focus-controller.stories.js
- src/lib/shadow-dom-utils.js
- test/controller/lost-focus-controller.test.js
- test/shadow-dom-utils.test.js
Fixes #575 
* This Reactive controller helps detect a focus loss situation when the focused element is removed from the DOM.
* You provide a query selector which will select the elements for which you're tracking removal.
* You provide a callback that will be fired when one of these elements is removed from the DOM. The callback is fired only if the deleted element had focus (or one of its children had focus)
* The callback will suggest a new element to focus on. It suggests the nearest element matching the same query selector.
Preview is [here](https://clever-components-preview.cellar-c2.services.clever-cloud.com/focus-lost-ctrl/index.html?path=/story/%F0%9F%95%B9%EF%B8%8F-controllers-focuslostcontroller--default-story)
* check the story
* check the storybook doc tab
> Add a FocusLostController

- CHANGELOG.md
- demo-smart/index.html
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.smart.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.stories.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.types.d.ts
- src/components/cc-tcp-redirection/cc-tcp-redirection.js
- src/components/cc-tcp-redirection/cc-tcp-redirection.stories.js
- src/components/cc-tcp-redirection/cc-tcp-redirection.types.d.ts
* apply the new design for component properties with typed states
* use the new defineSmartComponent for the smart definition
* move the skeleton logic to the cc-tcp-redirection component
> refactor(cc-tcp-redirection-form): rework state, types and smart for TCP redirection components

- .github/workflows/test-and-build.yml
The version 1 of `volta-cli/action` github action is so old that it doesn't work anymore: Running action fails with:
```
Run volta-cli/action@v1
with:
downloading volta@1.1.0
Object prototype may only be an Object or null: undefined
Waiting 18 seconds before trying again
Object prototype may only be an Object or null: undefined
Waiting 15 seconds before trying again
Error: Object prototype may only be an Object or null: undefined
```
Upgrading to version 4 resolve the issue. see [changelog](https://github.com/volta-cli/action/releases)
> ci(test): upgrade volta github action from version 1 to version 4

- .eslintrc.cjs
- CHANGELOG.md
- src/controllers/lost-focus-controller.stories.js
- test/controller/lost-focus-controller.test.js
Fixes #597.
We choose to deactivate the `no-new` rule.
> chore(eslint): update `no-new` rule to "off"

- CHANGELOG.md
- src/components/cc-select/cc-select.js
Fixes #604 
In the [Default Story - Select component - Preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-select/fix-disabled-placeholder/index.html?path=/story/%F0%9F%A7%AC-atoms-cc-select--default-story), you should be able to select a value from the first select, and then switch back to the placeholder. In other words, the placeholder is selectable.
In the [Required Story - Select component - Preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-select/fix-disabled-placeholder/index.html?path=/story/%F0%9F%A7%AC-atoms-cc-select--required), if you select a value, then you should not be able to switch back to the placeholder value. In other words, the placeholder is not selectable / disabled.
> fix(cc-select): disable placeholder option only when field is required

- CHANGELOG.md
- src/components/cc-select/cc-select.js
- src/components/cc-select/cc-select.stories.js
Fixes #587 
The whole code is basically a copy / paste from what @pdesoyres-cc has done for `cc-input-` a few weeks ago :wink:.
[Preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-select/fix-red-border-when-error/index.html?path=/story/%F0%9F%A7%AC-atoms-cc-select--simulation)
> fix(cc-select): add red border / focus ring when error slot is used

- src/components/cc-ssh-key-list/cc-ssh-key-list.smart.js
Improve UX with a better correlation between UI and API requests.
Previous behavior:
- request new key addition
- creation form disabled
- key successfully added
- creation form enabled
- request key lists refresh silently (ie. without skeleton state)
- key lists successfully refreshed
New behavior :
- request new key addition
- creation form disabled
- key successfully added
- request key lists refresh silently (ie. without skeleton state)
- key lists successfully refreshed
- creation form enabled
> fix(cc-ssh-key-list): improve UX when adding a new key

- tsconfig-typecheck-jsdoc.json
Fix #620.
Remove and update config properties not yet available in the current typescript version `~4.3.2`.
> fix: match typecheck tsconfig with typescript dependency version

- src/components/cc-stretch/cc-stretch.js
- src/components/cc-stretch/cc-stretch.stories.js
Fixes #657 
In a  local branch, the new "differentCssLayouts" should show all `cc-stretch` with the same `width` and `height`.
> fix(cc-stretch): rollback width max-content rule

- docs/cc-example-component.smart.md
Fixes #626 
* add a new "Events fired" section,
* remove the example telling that we can include the smart component in the `md` file (now that we use `demo-smart` system, it feels obsolete),
* use markdown syntax for most of the tables (first one cannot be done with markdown because it contains no headers?).
* code and markdown preview
> docs(cc-example-component-smart): add new Events fired section

- src/components/cc-email-list/cc-email-list.smart.js
- src/components/cc-env-var-form/cc-env-var-form.smart-config-provider.js
- src/components/cc-env-var-form/cc-env-var-form.smart-exposed-config.js
- src/components/cc-grafana-info/cc-grafana-info.smart.js
- src/components/cc-orga-member-list/cc-orga-member-list.smart.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.smart.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.smart.js
- src/lib/notifications.js
Fixes #663
- change the signature of the `notify` helper: move `target` to second parameter and added a default value (window).
- change the signature of the `notifyError` & `notifySuccess` helpers: remove the `target` parameter. It means these helpers always dispatch events from `window` now.
> feat(notifications): dispatch notify events from window by default

- src/components/cc-invoice-table/cc-invoice-table.js
Fixes #686 
When we flag an invoice as "wontpay" (meaning we stopped trying to get the money and considered the fight lost), it disappears from the displayed invoices entirely. The WONTPAY invoices should just be considered as pending ones.
> Add "WONTPAY" to pending statuses.

- src/components/cc-icon/cc-icon.js
Fixes #681
* 2 reviewers should be enough for this
The bug seems to correspond to what is described here:
https://bugs.webkit.org/show_bug.cgi?id=221234
The reduced test case can be found here: https://codepen.io/florian-sanders-cc/pen/OJwXxpW
If you check this on Safari 15, the `<svg>` element is not visible unless you uncomment the `flex-direction` rule or the `width` rule.
To fix this in the `cc-icon` I went for the explicit `width: 100%;` and `height: 100%` rules because I think it feels less magical than setting a different `flex-direction`.
edit: after checking with @roberttran-cc, the WebKit issue is not fixed with Safari 16 but our issue is. It might not be the same issue after all so let's not comment the WebKit issue.
> fix(cc-icon): force svg size to resolve safari 15 issue

- docs/adr/adr-0022-new-icon-system.md
Fixes #683.
Looking forward your feedback! :innocent: 
I tried to avoid adding too much details, to keep the document readable, but some parts may be lacking. :dizzy_face: 
**Question 1**
I decided to put @florian-sanders-cc's a11y part inside this ADR but, after some thoughts, should we do like the toaster's ADRs and split the content? I'm not sure it is relevant in this case, WDYT?
**Question 2** (from @florian-sanders-cc)
Some headings proposals, WDYT bis? Details in his [answer](https://github.com/CleverCloud/clever-components/pull/688#pullrequestreview-1242578225).
TO DO after review and before merging :
> docs(icon): add new icon system ADR

- src/components/cc-button/cc-button.js
- src/components/cc-header-orga/cc-header-orga.js
- src/components/cc-input-number/cc-input-number.js
- src/components/cc-input-text/cc-input-text.js
- src/components/cc-notice/cc-notice.js
- src/components/cc-pricing-estimation/cc-pricing-estimation.js
- src/components/cc-select/cc-select.js
- src/components/cc-toast/cc-toast.js
- src/components/cc-toggle/cc-toggle.js
- src/components/cc-zone-input/cc-zone-input.js
- src/styles/default-theme.css
- src/templates/cc-link/cc-link.js
Fixes #281
:tada: You may now review the code.
:monocle_face: You should also review most of the stories simply by tabbing through their content: the focus should always look like below
:art: If you don't like the styling of the focus outline, feel free to say so in a comment !
There are several ways to standardize our focus styling and I'm not sure which way to go.
The styling is made of two rules:
```css
outline: var(--color-blue-60) solid 2px;
outline-offset: 2px;
```
We'd like to apply these rules to every focusable element (minus some exceptions).
Currently, we use explicit selectors inside components like:
```css
.btn:not([aria-disabled='true']):focus {
outline: var(--cc-focus-outline);
outline-offset: var(--cc-focus-outline-offset);
}
```
The drawback is that it's easy to forget …
> fix(focus outline): use contrasted focus outline

- src/components/cc-ssh-key-list/cc-ssh-key-list.js
Fixes #703
Removing the `live()` directive and manually synchronizing the view and model does the job.
You'll have to checkout the branch to test locally with real data as you need to perform the delete or import action. Check the issue #703 for details on how to reproduce.
> fix(cc-ssh-key-list): creation form mistakenly updated

- .eslintrc.cjs
- docs/translations.example.js
- eslint-rules/i18n-always-template-literal-sanitize.js
- eslint-rules/i18n-shared.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #718.
Adds a custom `eslint` rules that detects and fixes improper usage of the `sanitize` function in translation files.
Most patterns can be detected, like the following:
```js
{
'cc-example.pattern-1': ({ foo }) => sanitize(`<em>improper ${foo} usage number 1</em>`),
'cc-example.pattern-2': ({ foo }) => {
return sanitize(`<em>improper ${foo} usage number 2</em>`);
},
'cc-example.complex-1': ({ foo }) => {
return foo
? sanitize(`<em>improper ${foo} complex usage number 1</em>`)
: `bar`;
},
'cc-example.complex-2': ({ foo }) => {
const foobar = sanitize(`<em>improper ${foo} complex usage number 2</em>`);
return foo ? foobar : `bar`;
},
}
```
Those patterns are automatically fixed (with the `lint:fix` npm task) to:
```js
{
'cc-example.pattern-1': ({ foo }) => sanitize`<em >improper …
```
> fix(eslint): check for improper sanitize function usage

- src/lib/define-smart-component-with-observables.js
- src/lib/define-smart-component.js
- src/lib/events.js
- src/lib/i18n.js
- src/lib/notifications.js
- src/lib/send-to-api.js
- src/lib/smart-manager.js
Fixes #746 
- review all files changed (changes are very simple so you can use the GitHub UI)
- 2 reviewers should be enough for this.
> docs(jsdoc): use the jsdoc syntax to flag optional parameters

- src/components/cc-addon-option/cc-addon-option.js
- src/components/cc-article-card/cc-article-card.js
- src/components/cc-article-list/cc-article-list.js
- src/components/cc-block-section/cc-block-section.js
- src/components/cc-block/cc-block.js
- src/components/cc-doc-card/cc-doc-card.js
- src/components/cc-doc-list/cc-doc-list.js
- src/components/cc-env-var-form/cc-env-var-form.js
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.js
- src/components/cc-error/cc-error.js
- src/components/cc-header-addon/cc-header-addon.js
- src/components/cc-header-app/cc-header-app.js
- src/components/cc-header-orga/cc-header-orga.js
- src/components/cc-input-number/cc-input-number.js
- src/components/cc-input-text/cc-input-text.js
- src/components/cc-invoice-table/cc-invoice-table.js
- src/components/cc-logsmap/cc-logsmap.js
- src/components/cc-map/cc-map.js
- src/components/cc-select/cc-select.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.js
- src/components/cc-tile-consumption/cc-tile-consumption.js
- src/components/cc-tile-scalability/cc-tile-scalability.js
- src/components/cc-zone-input/cc-zone-input.js
- src/styles/default-theme.css
- src/styles/info-tiles.js
Fixes #733
- check the commits (using GitHub should be enough),
- check all the components impacted (do the new border colors work for all of them?):
- `cc-addon-option.js`,
- `cc-article-card.js`,
- `cc-article-list.js`,
- `cc-block.js`,
- `cc-block-section.js`,
- `cc-doc-card.js`,
- `cc-doc-list.js`,
- `cc-env-var-form.js`,
- `cc-env-var-linked-services.js`,
- `cc-error.js`,
- `cc-header-addon.js`,
- `cc-header-app.js`,
- `cc-header-orga.js`,
- `cc-input-number.js`,
- `cc-input-text.js`,
- `cc-invoice-table.js`,
- `cc-logsmap.js`,
- `cc-map.js`,
- `cc-select.js`,
- `cc-ssh-key-list.js`,
- `cc-tile-consumption.js`,
- `cc-tile-scalability.js`,
- `cc-zone-input.js`,
- (all tiles).
<details>
<summary>Archived discussion</summary>
This one was a little bit trickier than anticipated in the …
> tokens: add neutral border colors and use them when relevant

- src/components/cc-input-number/cc-input-number.js
- src/components/cc-input-text/cc-input-text.js
- src/components/cc-select/cc-select.js
- src/styles/default-theme.css
Fixes #511 
Fixes #749 
This PR is fairly simple.
- review every commit
- check `cc-input-*` & `cc-select` stories (new very subtle change of border on hover, focus)
- check one of the `all form controls` stories and compare to prod to see the fix for readonly bg color.
> Tokens: add new neutral border colors for component states (disabled, hovered, focused)

- src/pricing/cc-pricing-header.js
Fixes #791 
Following #782, the zone select in `cc-pricing-header` did not have any default value set upon loading the zones.
This is a quick fix for this issue.
> fix(cc-pricing-header): force the value of the zone select

- src/components/cc-invoice/cc-invoice.js
Fixes #784
Move the `<template>` tag used within `cc-invoice` inside the `unsafeHTML` expression because Lit won't allow using expressions inside a `<template>` tag.
- code
- UI (in prod, invoice content = blank, in preview, invoice content = heading and text).
<details>
<summary>More info about the issue and the solution</summary>
The `<cc-invoice>` component allows developers to pass HTML through the `invoice.invoiceHtml` prop.
This feature used to work with Lit 1.X but it has been broken since we've migrated to Lit 2.X (components version 10 and upper).
The HTML fragment is supposed to be handled by `<cc-html-frame>` inside the `<cc-invoice>` component.
To pass HTML to `<cc-html-frame>`, you need to `slot` it inside a `<template>` tag like this:
```html
<cc-html-frame>
<template>your …
```
> fix(cc-invoice): `<template>` content is erased

- CHANGELOG.md
Fixes #793 
- Updates the changelog to retrieve entries from `7.13.0` and `7.13.1` versions.
- Adds a note to warn about the specificity of these versions. (Not sure about this message, feel free to suggest improvements as usual :hugs:)
> Changelog: add `7.13.0` and `7.13.1` versions

- demo-smart/cc-pricing-page/index.html
- src/components/cc-pricing-header/cc-pricing-header.smart.js
- src/components/cc-pricing-header/cc-pricing-header.smart.md
- src/components/cc-pricing-product-consumption/cc-pricing-product-consumption.smart.js
- src/components/cc-pricing-product-consumption/cc-pricing-product-consumption.smart.md
- src/components/cc-pricing-product/cc-pricing-product.smart-addon.js
- src/components/cc-pricing-product/cc-pricing-product.smart-addon.md
- src/components/cc-pricing-product/cc-pricing-product.smart-runtime.js
- src/components/cc-pricing-product/cc-pricing-product.smart-runtime.md
Fixes #798 
- Removes all `apiConfig` parameters from the newly updated pricing smart components.
- Review every commit.
@pdesoyres-cc I used `chore` as commit types because I did not want these to be part of the changelog (because we haven't released the changes I'm rolling back with this PR so it would be confusing to include these commits in the changelog).
=> Is there a better way to do this?
> cc-pricing-*: remove `apiConfig` from smart context parameters

- web-dev-server.config.js
Fixes #801
- Pull the branch, run `npm run storybook:dev` and check some of the stories like `cc-html-frame`. Open your dev tools console and you should see warnings like this:
> Web Dev Server: enable development mode for our dependencies

- package-lock.json
- package.json
- web-dev-server.config.js
Fixes #812 
- Upgrades the WDS dependency to `0.3.0`,
- Changes `nodeResolve` to `true` now that `exportConditions` is set to `development` by default.
2 reviewers should be enough.
- Check both commits,
- Run locally and check that you still have the Lit warning in your console when viewing a story.
> Web dev server: upgrade to `0.3.0` and switch back to `nodeResolve: true`

- src/components/cc-pricing-estimation/cc-pricing-estimation.js
- src/components/cc-pricing-page/cc-pricing-page.stories.js
- src/components/cc-pricing-product-consumption/cc-pricing-product-consumption.js
- src/components/cc-pricing-product/cc-pricing-product.js
- src/components/cc-pricing-product/cc-pricing-product.stories.js
- src/components/common.types.d.ts
- src/lib/product.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #796 
- Tweaks the code of `cc-pricing-product` to benefit from type checking and states.
- Updates the `cc-pricing-product` and `cc-pricing-estimation` components to use the `name` property if the feature code is not associated with a translation.
- Updates the `fake product` story to reflect this change.
- Updates all other product stories to filter features displayed (since features not translated used to be hidden, we did not have to explicitly filter them out before this change).
- Changes the `temporality` translation in English ("temporality" does not really mean what we wanted to convey here. I left it within the code to avoid an unnecessary breaking change, it's understandable for devs I think).
- Adds `Fake product` to the list of products displayed in the …
> cc-pricing-product: allow custom (not translated) features

- src/components/cc-addon-features/cc-addon-features.js
- src/components/cc-addon-features/cc-addon-features.types.d.ts
Fixes #815
2 reviewers should be enough.
Low priority, this change does not have to be released with `11.0.0` since it's just to fix a Webstorm issue.
> chore(cc-addon-features types): rename `Feature` to `AddonFeature`

- src/components/cc-tile-metrics/cc-tile-metrics.js
- test/helpers/accessibility.js
Fixes #821
Fixes #822
**Disclaimer:** the browser still logs `null` everytime a resize loop error happens. I tried to remove it but failed because we're patching the fake `window.onerror` of `Mocha` and it seems tricky. I stopped searching for a solution since we have a proper fix on its way and I don't think it's worth more efforts in the meantime as long as tests are fixed.
- 2 reviewers should be enough for this one,
- review the commits,
- check in local if tests are running fine (still verbose but I have no solutions for this),
- check that `cc-tile-metrics` is the same as in prod.
> fix(tests): add another resize loop error message to the ignore list

- demo-smart/cc-pricing-page/index.html
- demo-smart/index.html
- src/lib/product.js
Fixes #858
We have disabled MongoDB dev plans but the pricing API still returns it.
In the console, we rely on the fact that this plan is no longer attached to any zone to filter it.
We want to do the same within our pricing components. If a plan has no zone, then we shouldn't display it.
- review the commit,
- run locally and go to [localhost:6006/demo-smart/cc-pricing-page/](http://localhost:6006/demo-smart/cc-pricing-page/). => The "MongoDB" section should no longer display the `dev` plan.
- 2 reviewers should be enough for this one.
> fix(cc-pricing-product): filter out addon plans without zones

- src/components/cc-icon/cc-icon.js
* only try to update SVG aria attributes if SVG is in the DOM
* don't create several `<title>` tags when `accessibleName` changes
* apply aria attributes on SVG when `icon` changes
Fixes #770
> fix(cc-icon): improve SVG aria attributes behavior

- .github/workflows/preview.yml
- .github/workflows/publish.yml
- .github/workflows/test-and-build.yml
Fixes #874
As per https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file, we can easily move from `volta-cli/action` to `actions/setup-node`.
> ci: replace volta-cli/action by actions/setup-node

- package-lock.json
- package.json
- src/.eslintrc.cjs
- src/components/cc-input-date/cc-input-date.js
- src/components/cc-input-date/cc-input-date.stories.js
- src/components/cc-input-date/cc-input-date.test.js
- src/components/cc-input-date/cc-input-date.types.d.ts
- src/lib/date/date-formatter.js
- src/lib/date/date-utils.js
- src/lib/date/date.types.d.ts
- src/lib/utils.js
- src/stories/all-form-controls.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- test/date/date-formatter.test.js
- test/date/date-utils.test.js
- test/utils.test.js
- web-test-runner.config.js
> feat(cc-input-date): init component

- src/components/cc-toggle/cc-toggle.js
Fixes #896 
Fixes the extra margin above the component when using `inline` and when inside a grid area.
You cannot see the problem until you use the component in the exactly explained situation.
See the issue details to have an example of code that reproduces the bug.
To help you, here is a story you can add to the code to see the problem, and to check if it has been fixed:
```javascript
export const grid = makeStory(conf, {
// language=CSS
css: `
.grid {
display: grid;
grid-template-areas:
'area1 area3'
'area2 area3';
grid-template-columns: 250px 1fr;
grid-template-rows: max-content 1fr;
gap: 1em;
}
.area1 {
grid-area: area1;
background-color: indianred;
}
.area2 {
grid-area: area2;
background-color: steelblue;
}
.area3 {
grid-area: area3;
background-color: darkseagreen;
}
`,
dom: …
```
> fix(cc-toggle): fix extra margin on top of cc-toggle

- docs/adr/adr-0025-moving-away-from-fieldset-legend.md
We faced an issue with weird spaces added on top of the `<cc-toggle>` component when used in a grid context.
We decided to rely on `ARIA` for semantics instead of `<fieldset>` / `<legend>` so we can style it in a more robust way.
This ADR explains this and contains screen reader tests that prove this method is ok for accessibility.
> docs(ADR): add ADR about `<fieldset>` & `<legend>`

- src/lib/i18n-sanitize.js
This fixes an issue with Chrome >= 120
Please read the issue for more info about the bug. This will make the solution easier to understand.
Fixes #906
- review the commit,
- run the tests locally with chrome >= 120 on this branch vs on the main branch.
Thanks @Galimede for your help when trying to reproduce this issue and for trying to find the reason in the chrome changelog :wink:
> fix(i18n-sanitize): handle cases where origin equals empty string

- package-lock.json
- package.json
- src/lib/events.js
- test/event.test.js
Fixes #902 
When dispatching custom events, we check if the element is a beta component (`^cc-.+-beta$`).
If it the case, the name of the event will be prefixed by the component name **without** the `-beta` suffix.
There are 2 commits:
* The first one adds unit tests on `dispatchCustomEvent` function.
* The second one implements the feature itself.
* With Storybook, with Action addon, check that [this <cc-logs-beta> story](https://clever-components-preview.cellar-c2.services.clever-cloud.com/event-beta/index.html?path=/story/%F0%9F%9A%A7-beta-%F0%9F%9B%A0-logs-cc-logs-beta--data-loaded-with-many-metadata-with-wrap-lines) emits the right events when
* scrolling to the bottom: `onCcLogsFollowChange: "false"`
* scrolling up: `onCcLogsFollowChange: "true"`
2 reviewers should …
> chore: handle beta components when firing custom events 

- package-lock.json
Small bump to the package lock that we had forgotten following the addition of the `chai-as-promised` dependency.
> chore(package-lock): update lock file following dependency addition

- src/components/cc-badge/cc-badge.js
Fixes #934
- Reviewing the commit should be enough,
- 1 reviewer should be enough.
> fix(cc-badge): use `iconA11yName` in `iconAccessibleName` getter/setter

- rollup/rollup-common.js
Fixes #898
- Checkout branch
- Run `(export VERSION=12.0.0 && npm run cdn-release:build)` task
- Check the `dist-cdn/cc-remix.icons-{HASH}.js` file contents
- It should no more include all Remix icons and only include icons actually used in our Clever Components (43 icons)
Also impacts the NPM build: remix icons are no more "officially" included. More precisely, they are still available but not at the project root. This behavior is intended.
Two will be sufficient.
> build(cdn): remove generated icon files from rollup config

- demo-smart/index.html
- src/components/cc-addon-linked-apps/cc-addon-linked-apps.js
- src/components/cc-addon-linked-apps/cc-addon-linked-apps.smart.js
- src/components/cc-addon-linked-apps/cc-addon-linked-apps.stories.js
- src/components/cc-addon-linked-apps/cc-addon-linked-apps.types.d.ts
- src/components/common.types.d.ts
Fixes #918 (which is part of #708)
Also fixes a part of #917.
* rework the properties to use our new way of implementing component states (this is a breaking change)
* migration of the smart component with the new design (no RxJs)
* remove incoming confusion with Instance type (see #917).
* code
* check for regressions
> refactor(cc-addon-linked-apps): migrate to the new smart component design

- demo-smart/index.html
- src/components/cc-article-list/cc-article-list.js
- src/components/cc-article-list/cc-article-list.smart.js
- src/components/cc-article-list/cc-article-list.smart.md
- src/components/cc-article-list/cc-article-list.stories.js
- src/components/cc-article-list/cc-article-list.types.d.ts
> refactor(cc-article-list)!: migrate to the new smart component design

- docs/adr/adr-0018-how-to-give-feedback-after-a-user-action.md
- docs/adr/adr-0019-how-to-make-toaster-accessible.md
- docs/adr/adr-0020-making-the-component-theme-customisable.md
- docs/adr/adr-0023-adding-stylelint.md
- docs/adr/adr-0025-moving-away-from-fieldset-legend.md
- docs/getting-started/accessibility.md
- docs/getting-started/breaking-change-policy.md
- docs/getting-started/design-tokens.md
- docs/getting-started/notification-system.md
- package.json
- src/components/cc-email-list/cc-email-list.smart.md
- src/components/cc-env-var-form/cc-env-var-form.smart-config-provider.md
- src/components/cc-env-var-form/cc-env-var-form.smart-env-var-addon.md
- src/components/cc-env-var-form/cc-env-var-form.smart-exposed-config.md
- src/components/cc-grafana-info/cc-grafana-info.smart.md
- src/components/cc-invoice-list/cc-invoice-list.smart.md
In #952, I forgot that I had hard coded where storybook should be built.
This means storybook is always built inside a `storybook-static` folder.
This works well for previews and dev but it does not work for our production app.
<details>
<summary>More info about the output folder issue</summary>
Our production app is set to only handle requests from: `https://[www.]clever-cloud.com/doc/clever-components/`.
In other words, we rely on [prefix routing](https://developers.clever-cloud.com/doc/administrate/domain-names/#prefix-routing). For this to work correctly on the Clever Cloud side, the app must contain a folder corresponding to the path we have defined (the part after the domain in the example above). That is to say:
`/doc/clever-components/`
This is why we had the following command …
> Storybook: fix build path & docs URLs

- src/components/cc-input-date/cc-input-date.js
- src/components/cc-input-date/cc-input-date.stories.js
- src/components/cc-input-number/cc-input-number.js
- src/components/cc-input-number/cc-input-number.stories.js
- src/components/cc-input-text/cc-input-text.js
- src/components/cc-input-text/cc-input-text.stories.js
- src/components/cc-select/cc-select.js
- src/components/cc-select/cc-select.stories.js
- src/components/cc-toggle/cc-toggle.js
- src/components/cc-toggle/cc-toggle.stories.js
- src/stories/all-form-controls.js
Fixes #888.
Is the feature properly working & rendered on screen.
Does the feature introduces visual regression (excluding "Visual breaking changes").
Updated components:
- `cc-input-text`
- `cc-input-number`
- `cc-input-date`
- `cc-select`
- `cc-toggle`
UI review:
- for the introduced feature, a dedicated story "Custom label style" has been added, displaying relevant cases ;
- for regression check, compare stories between the preview & the current release.
Code review: there is one commit per component so it's quite straightforward.
<details>
<summary>(previous topic on "visual breaking changes")</summary>
Actually, this feature needed a change in the component global layout, impacting many cases but especially when label is displayed inline.
Thus introducing potential "visual breaking …
> Add label style customization for cc-input-text & similar components

- .githooks/pre-push
This PR adds protection on direct push on the master branch. It doesn't prevent developers from doing it (it can sometimes be necessary). But a confirmation will be required when pushing on the master branch.
> chore: protect master branch from push

- .storybook/main.js
- cem/generate-cem-vite-plugin.js
- package-lock.json
- package.json
Fixes #989 
- Improve the `viteFinal` config handling. We rely on the `mergeConfig` helper from vite to avoid erasing parts of the builder config by mistake. This is on par with the Storybook docs (see [viteFinal - Storybook](https://storybook.js.org/docs/api/main-config-vite-final#options)).
- Add vite to our dev dependencies. We need to for the `mergeConfig` helper (although we could rely on the `storybook` node modules one) + the types. Note that since v8.0.0, storybook automatically adds vite to the dev dependencies so this feels like the right move anyway?
- Regenerate CEM everytime a component is updated (in dev mode only). (see #989 for more info + the comments within the code to review).
- Check both commits (the first commit's diff is not easy to read, you might as well just …
> Storybook (dev server): refresh CEM when a component is updated

- .storybook/preview.js
- src/stories/lib/autodocs-template.jsx
- tsconfig.json
Fixes #997 
- Removes embedded stories from auto generated docs
- 2 reviewers should be enough,
- Review the commit,
- Check both the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/storybook/remove-embedded-stories-from-docs/index.html) and locally that docs do not contain stories
> chore(storybook): remove embedded stories from autodocs

- src/components/cc-button/cc-button.js
- src/templates/cc-link/cc-link.js
Fixes #994 
- cc-button: Prevent click events from going through in skeleton / waiting mode.
- cc-button: Make sure the text is not visible in link + skeleton mode.
- cc-link: Unset the `href` attribute in skeleton mode.
- 2 reviewers should be enough,
- review both commits,
- compare the [cc-addon-backups - skeleton story - Production](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-addon-cc-addon-backups--skeleton) and [cc-addon-backups - skeleton story - Preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/links/fix-skeleton/index.html?path=/story/%F0%9F%9B%A0-addon-cc-addon-backups--skeleton).
- In prod, when clicking the first blue skeleton within a backup row, the page is refreshed. It shouldn't be the case in preview.
- In …
> cc-button/cc-link: prevent activation in skeleton mode

- package-lock.json
- package.json
- src/components/cc-toast/cc-toast.js
- tsconfig.json
Fixes #950 
- Upgrades `custom-elements-manifest/analyzer` to `0.9.4`,
- Upgrades `typescript` to `5.4.2`,
- Upgrades `ts-lit-plugin` to `2.0.2`,
- Updates the `tsconfig.json` file to enable options we could not use before,
- Fixes the only breaking change that impacted us following this upgrade.
- Check that `ts-lit-plugin` is still working fine, for instance: removing the `cc-icon` import within the `cc-badge` should trigger an error where `<cc-icon>` is used,
- Check some doc stories using the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cem-typescript/upgrade/index.html) (we have already checked the diff + stories that may have been impacted),
- 2 reviewers (other than @Galimede & me) should be enough for this one.
> CEM & TypeScript: upgrade

- cem/generate-cem-vite-plugin.js
Fixes #1026
- Fixes an error that happens when modifying a component file while browsing `sandbox` or `demo-smart`.
- On the master branch:
- go to localhost:6006/demo-smart/,
- modify a component (any component, it does not have to be the one you are viewing, it does not have to be related to a smart demo),
- you should get the following error `Cannot read properties of undefined (reading 'invalidationState')`.
- :warning: Don't forget to have your smart component env vars sourced otherwise the error will not be triggered!
- Do the same on this branch, you should get no error.
- 2 reviewers should be enough for this one.
> chore(storybook): prevent error with HMR and `sandbox` / `demo-smart`

- src/components/cc-addon-admin/cc-addon-admin.js
Fixes #1042
- Removes improper spacing between the danger zone paragraphs.
- Check the preview (narrow + large viewport),
> fix(cc-addon-admin): remove improper spacing within the danger zone

- demo-smart/index.html
- changes the `app-node` & `app-play` app ids within the demo-smart file because previous demo apps have been deleted,
- adds `grafanaBaseLink` & `consoleBaseLink` to the context so they can be used to review the `cc-tile-metrics` component.
- Run the storybook locally and check the demo-smart > `tile-metrics`  page. With `app-node`, metrics should show up after a minute or so. With `app-play`, the component should show a message saying the app is stopped,
- One review should be enough for this one.
**Note:** this PR does not modify the `cpu-load-bench` app because I don't know if we still want to use it or not (it may be overkill now that the component is stable and we may not want to keep this app running constantly for nothing, I'll discuss it with Mathieu later …
> chore(demo-smart): update app ids

- src/components/cc-tile-metrics/cc-tile-metrics.js
- src/components/cc-tile-metrics/cc-tile-metrics.smart.js
- src/components/cc-tile-metrics/cc-tile-metrics.stories.js
- src/components/cc-tile-metrics/cc-tile-metrics.types.d.ts
- Refactors the `cc-tile-metrics` component to implement our new state structure,
- Implements TypeChecking within the `cc-tile-metrics` component and its stories.
- Compare the [prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-overview-cc-tile-metrics--default-story) to the [preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-tile-metrics/state-migration/index.html?path=/story/%F0%9F%9B%A0-overview-cc-tile-metrics--default-story),
- Don't forget to check the smart using the `demo-smart` …
> refactor(cc-tile-metrics)!: rework properties to avoid impossible states

- src/components/cc-tile-requests/cc-tile-requests.js
- src/components/cc-tile-requests/cc-tile-requests.stories.js
- src/components/cc-tile-requests/cc-tile-requests.types.d.ts
- Refactors the `cc-tile-requests` component to implement our new state structure,
- Implements TypeChecking within the `cc-tile-requests` component and its stories.
- Compare the [prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-overview-cc-tile-requests--default-story) to the [preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-tile-requests/state-migration/index.html?path=/story/%F0%9F%9B%A0-overview-cc-tile-requests--default-story).
> refactor(cc-tile-requests)!: rework properties to avoid impossible states

- src/components/cc-matomo-info/cc-matomo-info.js
- src/components/cc-matomo-info/cc-matomo-info.stories.js
- src/components/cc-matomo-info/cc-matomo-info.types.d.ts
- Refactors the `cc-matomo-info` component to implement our new state structure,
- Implements TypeChecking within the `cc-matomo-info` component and its stories.
- Compare the [prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-addon-cc-matomo-info--default-story) to the [preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-matomo-info/state-migration/index.html?path=/story/%F0%9F%9B%A0-addon-cc-matomo-info--default-story).
> refactor(cc-matomo-info)!: rework properties to avoid impossible states

- src/components/cc-article-card/cc-article-card.js
- src/components/cc-article-card/cc-article-card.stories.js
- src/components/cc-article-card/cc-article-card.types.d.ts
- src/components/cc-article-list/cc-article-list.js
- src/components/cc-article-list/cc-article-list.smart.js
- src/components/cc-article-list/cc-article-list.stories.js
- src/components/cc-article-list/cc-article-list.types.d.ts
- Refactors the `cc-article-list` & `cc-article-card` components to implement our new state structure,
- Implements TypeChecking within the `cc-article-list` & `cc-article-card` components and their stories.
- Compare the [cc-article-card prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-homepage-cc-article-card--default-story) to the [preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-article-list/state-migration/index.html?path=/story/%F0%9F%9B%A0-homepage-cc-article-card--default-story), …
> refactor(cc-article-components)!: rework properties to avoid impossible states

- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.smart.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.stories.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.types.d.ts
- src/components/cc-tcp-redirection/cc-tcp-redirection.js
- src/components/cc-tcp-redirection/cc-tcp-redirection.stories.js
- src/components/cc-tcp-redirection/cc-tcp-redirection.types.d.ts
- Refactors the `cc-tcp-redirection` and `cc-tcp-redirection-form` components to implement our new state structure,
- Implements TypeChecking within the `cc-tcp-redirection`  and `cc-tcp-redirection-form` components and their stories,
- Fixes all data loaded stories (the last redirection item was supposed to be private but was not properly set).
- Check the commits (the diff may not be easy to read so you can review the final result locally if you prefer),
- If you check it locally, you should not get any Typescript error within the components files or the story files,
- Compare the `cc-tcp-redirection` [prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-tcp-redirections-cc-tcp-redirection--default-story&globals=locale:fr) to the [preview …
> refactor(cc-tcp-components)!: rework properties to avoid impossible states

- src/components/cc-header-orga/cc-header-orga.js
- src/components/cc-header-orga/cc-header-orga.stories.js
- src/components/cc-header-orga/cc-header-orga.types.d.ts
- Refactors the `cc-header-orga` component to implement our new state structure,
- Implements TypeChecking within the `cc-header-orga` component and its stories.
- Compare the [prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-overview-cc-header-orga--default-story) to the [preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-header-orga/state-migration/index.html?path=/story/%F0%9F%9B%A0-overview-cc-header-orga--default-story).
> refactor(cc-header-orga)!: rework properties to avoid impossible states

- src/components/cc-doc-card/cc-doc-card.js
- src/components/cc-doc-card/cc-doc-card.stories.js
- src/components/cc-doc-card/cc-doc-card.types.d.ts
- src/components/cc-doc-list/cc-doc-list.js
- src/components/cc-doc-list/cc-doc-list.stories.js
- src/components/cc-doc-list/cc-doc-list.types.d.ts
- Refactors the `cc-doc-card` and `cc-doc-list` components to implement our new state structure,
- Implements TypeChecking within the `cc-doc-card`  and `cc-doc-list` components and their stories.
- Check the commits (the diff may not be easy to read so you can review the final result locally if you prefer),
- If you check it locally, you should not get any Typescript error within the components files or the story files,
- Compare the `cc-doc-card` [prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-homepage-cc-doc-card--default-story) to the [preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-doc-list/state-migration/index.html?path=/story/%F0%9F%9B%A0-homepage-cc-doc-card--default-story) and the `cc-doc-list` …
> refactor(cc-doc-components)!: rework properties to avoid impossible states

- src/components/cc-addon-admin/cc-addon-admin.js
- src/components/cc-addon-admin/cc-addon-admin.stories.js
- src/components/cc-addon-admin/cc-addon-admin.types.d.ts
- src/components/common.types.d.ts
- Refactors the `cc-addon-admin` component to implement our new state structure,
- Implements TypeChecking within the `cc-addon-admin` component and its stories,
- Adds 2 new stories because we handle name / tag updates a little bit differently: we now set the related submit button in waiting mode ("update name" button for name update for instance) and disable other buttons while waiting,
- Updates the simulation story to reflect the new stories (simulates a name update, then a tag update, then an add-on deletion).
- Compare the [prod …
> refactor(cc-addon-admin)!: rework properties to avoid impossible states

- src/components/cc-invoice-list/cc-invoice-list.js
- src/components/cc-invoice-list/cc-invoice-list.smart.js
- src/components/cc-invoice-list/cc-invoice-list.stories.js
- src/components/cc-invoice-list/cc-invoice-list.types.d.ts
- src/components/cc-invoice-table/cc-invoice-table.js
- src/components/cc-invoice-table/cc-invoice-table.stories.js
- src/components/cc-invoice-table/cc-invoice-table.types.d.ts
- src/components/cc-invoice/cc-invoice.stories.js
- src/components/common.types.d.ts
- src/stories/fixtures/invoices.js
- Refactors the `cc-invoice-table` component to implement our new state structure,
- Refactors the `cc-invoice-list` component to adapt to the `cc-invoice-table` changes,
- Implements TypeChecking within the `cc-invoice-table` & `cc-invoice-list` components and their stories.
- Compare the [cc-invoice-table prod stories](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-invoices-cc-invoice-table--default-story) to the [cc-invoice-table preview stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-invoice-list/state- …
> refactor(cc-invoice-components): !: rework properties to avoid impossible states

- src/components/cc-addon-credentials/cc-addon-credentials.js
- src/components/cc-addon-credentials/cc-addon-credentials.stories.js
- src/components/cc-addon-credentials/cc-addon-credentials.types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1068
- Changes the `addonType` value for Materia KV from `materiadb-kv` to `materia-kv`
- Check the Materia KV story in preview,
> fix(cc-addon-credentials)!: change `addonType` value for Materia KV

- test/helpers/accessibility.js
- test/helpers/get-stories.js
Fixes #1069 
- Adapt to a storybook breaking change by providing the story name to the automated test helpers another way.
- You may run the tests for a given component like this: `npm run test:watch src/components/cc-badge/cc-badge.test.js` and press `D` to debug within Chrome. There, you should see the story name within the browser logs (see screenshot below)
- 1 reviewer should be enough for this one :wink:
> chore(test/helpers): pass story names and use them

- src/components/cc-tile-status-codes/cc-tile-status-codes.smart.js
Fixes #1085
- Fixes the `cc-tile-status-codes` smart component,
- Run this branch / PR locally 
- check the `demo-smart` page,
- select the component & `app-node` or `app-play`,
- There should be no error + the component should be showing a chart (you can compare on master, doing the same thing throws an error).
- 1 reviewer should be enough
> fix(cc-tile-status-codes.smart): pass `warpConfig` instead of `apiConfig`

- src/components/cc-logs-instances/cc-logs-instances.js
Fixes #1070
Since I could not reproduce the bug in real life, I just protected the grid layout from being broken when the state is not supported.
> fix(cc-logs-instances): make sure deploying instances grid layout is never broken

- .storybook/preview-head.html
- docs/contributing/wc-guidelines.md
- Go to the ["wc-guidelines" preview page](https://clever-components-preview.cellar-c2.services.clever-cloud.com/docs/web-component-guidelines-state/index.html?path=/story/%F0%9F%91%8B-contributing-web-components-guidelines--page) and review the "How to deal with complex component states / data?" section
> docs(wc-guidelines): add a section about component state

- src/components/cc-tile-metrics/cc-tile-metrics.js
Fixes #1092
- The component displayed the average CPU usage within last 24h instead of memory usage (see screenshot below). This PR fixes this issue.
- Check locally with `demo-smart`,
- 1 reviewer should be enough.
> fix(cc-tile-metrics): use the correct value for average memory usage within last 24h

- src/components/cc-logs/cc-logs.js
- src/components/cc-logs/logs-controller.js
- src/components/cc-logs/logs-input-controller.js
This PR contains som easy quick wins:
- add `Home` and `End` keystrokes (Fixes #1009)
- feat(cc-logs): add ctrl+A keystroke for selecting all log lines (Fixes #1008)
- feat(cc-logs): select whole log line with triple click (Fixes #1006)
- feat(cc-logs): make copy button more visible (Fixes #1012)
> cc-logs: easy-quick-wins

- src/components/cc-input-date/cc-input-date.js
- src/components/cc-input-number/cc-input-number.js
- src/components/cc-input-text/cc-input-text.js
When the `Enter` key is typed, we ask for the underlying form to be submitted. It fails when the input is not into a `<form>` element.
This PR fixes that by requesting a form submit only if a `<form>` is attached to the input ElementInternals.
Use Storybook and type `Enter` in either a `cc-input-text`, `cc-input-date`, or `cc-input-number`. Check for errors in the browser console.
Only 1 reviewer is enough.
> fix(cc-input-*): fix Enter keystroke when not into a form element

- docs/adr/adr-0026-introducing-prettier.md
The Prettier ADR wasn't in the correct category and appeared in the index.
* Check the [production Storybook](https://www.clever-cloud.com/doc/clever-components/?path=%2Fdocs%2Fadr-0026-introducing-prettier-as-a-formatter--docs), you should see that the ADR is in the index.
* Checkout the branch and run your storybook locally, you should now see it in the correct directory  
It's a quick fix, one reviewer should be enough. :slightly_smiling_face:
> fix: prettier adr wasn't in the correct directory

- demo-smart/index.html
- src/components/cc-domain-management/cc-domain-management.js
- src/components/cc-domain-management/cc-domain-management.smart.js
- src/components/cc-domain-management/cc-domain-management.smart.md
- src/components/cc-domain-management/cc-domain-management.stories.js
- src/components/cc-domain-management/cc-domain-management.test.js
- src/components/cc-domain-management/cc-domain-management.types.d.ts
- src/lib/domain.js
- src/lib/i18n-sanitize.js
- src/stories/fixtures/domains.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- tsconfig.json
Fixes #1095 
- Check the code (since these are mostly new files, it might be more convenient to review locally),
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-domain-management/init/index.html?path=/story/%F0%9F%9B%A0%EF%B8%8F-domains-cc-domain-management--default-story):
- all stories,
- both French & English,
- different viewport sizes.
- Proceed with the [QA](https://docs.google.com/spreadsheets/d/1Gjb7LwqOx3ZDNDFt2C347wmF2pjk7IuFgFvaFEd2BAM/edit?gid=1267293083#gid=1267293083),
- note that this QA should be done using the console (links to specific cases are available within the docs).
- At least 4 or 5 reviews are required for this PR.
- Component naming, should we got for `cc-domain-list` instead? It feels more consistent even though …
> cc-domain-management: init component

- src/components/cc-toast/cc-toast.js
- src/components/cc-toast/cc-toast.stories.js
Fixes #1127
- Adds default margins for paragraphs within the `cc-toast` component so that paragraphs created from translations don't get the default native paragraph margin (which is too big).
- You may review the `cc-toast--with-sanitized-html-message` story and you can also go to the `demo-smart` => domain-management => add a new domain and check the info toast content.
> fix(cc-toast): decrease paragraph margins

- src/components/cc-input-text/cc-input-text.js
Fixes #1130
- Check the code.
- Check the `cc-input-text` stories in the preview.
- Check some components using `cc-input-text` (for instance `cc-addon-admin`).
2 reviewers should be enough.
> fix(cc-input-text): match text and input

- src/components/cc-domain-management/cc-domain-management.js
Fixes #1126
- Slightly improves the appearance of the `cc-domain-management` component when viewport is reduced.
- Cards no longer have the same height between different rows,
- Buttons wrap below badges when there not enough space,
- Badges span through the whole width of their container unless there is not enough space (in which case they wrap below each other).
- Review the commit,
- Compare [prod - data loaded with http-only domain](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-domains-cc-domain-management--data-loaded-with-http-only-domain) & [preview -  data loaded with http-only domain](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-domain-management/improve-responsive/index.html?path=/story/%F0%9F%9B%A0-domains-cc-domain-mana …
> fix(cc-domain-management): improve responsive aspect

- src/components/cc-domain-management/cc-domain-management.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1134
- Changes the display of A Record values within the `DNS configuration` section to show all of them within a single `<cc-input-text>` element in `multi` (`textarea` mode).
- This makes it possible for users to copy all values at once.
- Review the commit,
- Check the [preview (bottom of the screen, within the DNS config section)](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-domain-management/textarea-for-a-records/index.html?path=/story/%F0%9F%9B%A0-domains-cc-domain-management--data-loaded-with-http-only-domain)
- Give your opinion on whether you want to see this merged or not :
- :+1: Yes merge this, it's better this way.
- :-1: No, don't merge this. We should stick with separate `<cc-input-text>`  for each A record value + add a global copy …
> feat(cc-domain-management): display all A Records within a single input

- src/components/cc-domain-management/cc-domain-management.js
- src/components/cc-domain-management/cc-domain-management.stories.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- Updates `cc-domain-management`'s texts with modifications suggested by @davlgd.
- Check the component in [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-domain-management/fix-translations/index.html?path=/story/%F0%9F%9B%A0-domains-cc-domain-management--data-loaded-with-http-only-domain), the sections to read carefully are:
- the one above the form,
- the warning notice for http-only domains,
- the info notice within the `DNS config` section,
- the desc on the left within `DNS config > CNAME` & `DNS config > A Records`.
- 1 reviewer is enough for this one.
> fix(cc-domain-management): fix typo & improve texts

- web-test-runner.config.js
With Chromium / Chrome > 127, it seems that our tests timeout randomly.
The tests that timeout are never the same, it's always within the second half of the testing phase + the last 3 tests.
The [issue #2403 on the @web repo](https://github.com/modernweb-dev/web/issues/2403) states that setting concurrency > 1 makes tests timeout. We never had the issue before but it's clear that setting `concurrency: 1` fixes the issue now so we'll go with that for the time being.
This may slow down tests so it should only be a temporary solution.
- Check that CI tests pass,
- Run tests locally and check that they pass as well,
- Check the commit code,
> Web Test Runner: tests timeout randomly

- cem/support-typedef-jsdoc-utils.js
- cem/support-typedef-jsdoc.js
- cem/test/fixtures/cc-test-component.types.d.ts
- cem/test/support-typedef-jsdoc-utils.test.js
- src/components/cc-addon-backups/cc-addon-backups.js
- src/components/cc-logs-application-view/cc-logs-application-view.js
- src/components/cc-logs-application-view/cc-logs-application-view.types.d.ts
* When using bare imports in the types, the plugin tried to look up in the corresponding file the subtypes. However, we don't want that and only want to use the type from the bare import.
* This PR also makes the plugin exit to `1` if an error has been detected.
> fix(cem-types-plugin): ignore non relative path imports

- sandbox/forms/form-demo-with-smart-component.js
- src/components/cc-addon-linked-apps/cc-addon-linked-apps.smart.js
- src/components/cc-article-list/cc-article-list.smart.js
- src/components/cc-domain-management/cc-domain-management.smart.js
- src/components/cc-email-list/cc-email-list.smart.js
- src/components/cc-env-var-form/cc-env-var-form.smart-config-provider.js
- src/components/cc-env-var-form/cc-env-var-form.smart-env-var-addon.js
- src/components/cc-env-var-form/cc-env-var-form.smart-exposed-config.js
- src/components/cc-env-var-form/cc-env-var-form.types.d.ts
- src/components/cc-grafana-info/cc-grafana-info.smart.js
- src/components/cc-grafana-info/cc-grafana-info.types.d.ts
- src/components/cc-invoice-list/cc-invoice-list.smart.js
- src/components/cc-invoice/cc-invoice.smart.js
- src/components/cc-jenkins-info/cc-jenkins-info.smart.js
- src/components/cc-orga-member-list/cc-orga-member-list.smart.js
- src/components/cc-pricing-header/cc-pricing-header.smart.js
- src/components/cc-pricing-product-consumption/cc-pricing-product-consumption.smart.js
- src/components/cc-smart-container/cc-smart-container.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.smart.js
- src/components/cc-tcp-redirection-form/cc-tcp-redirection-form.smart.js
- src/components/cc-tile-metrics/cc-tile-metrics.smart.js
- src/components/cc-tile-status-codes/cc-tile-status-codes.smart.js
- tasks/typechecking-stats.js
- tsconfig.ci.json
- Fixes typechecking issues within most of smart components,
- Adds all smart components that pass typechecking to the CI typechecking.
- Check every commit starting from `refactor(cc-smart-container): typecheck`,
- That's it, CI takes care of the rest :wink:
> refactor: Typecheck smart components in CI

- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1173
- Changes the docs link leading to the `cleverapps` section for domain names,
- Review is not essential,
- Wait for docs confirmation to make sure the link anchor is the proper one.
> fix(cc-domain-management): update `cleverapps` docs link

- src/components/cc-invoice-list/cc-invoice-list.stories.js
- src/components/cc-invoice-table/cc-invoice-table.js
- src/components/cc-invoice-table/cc-invoice-table.stories.js
- src/components/cc-invoice/cc-invoice.js
- src/components/cc-invoice/cc-invoice.smart.js
- src/components/cc-invoice/cc-invoice.stories.js
- src/components/cc-invoice/cc-invoice.types.d.ts
- src/components/common.types.d.ts
- src/lib/i18n/i18n-number.js
- src/lib/utils.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1169
- Adds a `currency` property to the loaded state of `cc-invoice`,
- Within the `cc-invoice` smart component, pass down `currency` from the API response to the UI component,
- Within the `cc-invoice-table` component, pass the `currency` property to translation functions,
- Adds stories to showcase that these components handle multiple currencies.
- Check the new stories (dollar currency for `cc-invoice-list`, `cc-invoice-table`, `cc-invoice`),
- Check the `demo-smart` > `cc-invoice`. You can mock an API call return USD instead of 'EUR' if you want (not mandatory since I've done it already),
- 2 reviewers should be enough for this one but I need our Pricing expert (aka @Galimede) review :sunglasses:
> feat(cc-invoice): add `currency` as part of the `state`

- src/components/cc-block/cc-block.js
- src/components/cc-domain-management/cc-domain-management.js
- src/components/cc-invoice/cc-invoice.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- `cc-env-var-form` : adds plural to "variable" in description text and removes unnecessary "En savoir plus / Learn more" in description text,
- `cc-block` : removes margin bottom,
- `cc-domain-management` : reverts to initial gap,
- `cc-invoice`: remove unnecessary padding.
- Check the components in [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-block/fix-component/index.html)
> fix(cc-block): fix css and description text

- src/components/cc-domain-management/cc-domain-management.smart.js
Fixes #1213
- Fixes an issue when trying to set a domain that you have just associated to an app as primary.
- Go to `localhost:6006/demo-smart/`, `cc-domain-management`, `app-node`:
1. add a new domain (with no path prefix),
2. mark it as primary,
3. you should get no error,
4. try to mark others as primary, delete some domains, nothing should throw any error.
> fix(cc-domain-management): allow newly added domain to be marked as primary

- src/components/cc-block/cc-block.js
- src/components/cc-header-addon/cc-header-addon.js
- src/components/cc-header-app/cc-header-app.js
As noticed by @Galimede, the logos in the `cc-header-addon` footer were bigger than before since the component were adapted with the new `cc-block`. During the refactoring, I have removed the `messages` class the was applying a font-size, this PR revert it with the necessery properties to match the old footer design.
> fix(cc-header-addon): revert `messages` class

- src/components/cc-zone-picker/cc-zone-picker.js
- src/components/cc-zone-picker/cc-zone-picker.stories.js
* This PR introduces a `disabled` prop to disable the whole form
* This PR introduces a `readonly` prop to disable the whole form except the selected value
* This PR makes the component always select the first value if no value has been set 
* Check the commit
* Check the stories (disabled, partDisabled, readonly, noPreselectedValue)
> feat(cc-zone-picker): add disabled and readonly modes

- src/components/cc-header-addon/cc-header-addon.js
- src/components/cc-header-app/cc-header-app.js
- src/components/cc-zone/cc-zone.js
The #1219 PR removed `align-items: center` from `.messages` in `cc-header-app` because my feedback was not clear.
This PR reverts it and improves the `cc-zone` alignment in `cc-header-app` & `cc-header-addon`. 
The alignment issue of the `cc-zone` is very subtle and it should be handled from the `cc-zone` component directly but this would require to add a wrapper instead of flexing the host directly, and it would probably lead to a breaking change so I'll create a quick win issue that we can squeeze in the next breaking change release (pricing probably).
This is why this PR handles it from outside the `cc-zone` in the meantime.
- Compare prod and preview default stories for `cc-header-app` & `cc-header-addon` (footer) and check the alignment is better in preview (may need to zoom a bit).
> refactor(cc-header-app): revert `align-items` removal

- src/components/cc-toast/cc-toast.js
Fixes #1232
- Replaces the hard coded `border-radius` value with the `--cc-border-radius-default`
- Check the preview,
- 1 reviewer is enough.
> fix(cc-toast): replace hard coded border radius with `--cc-border-radius-default`

- docs/contributing/wc-guidelines.md
- Fixes the errors in the code examples within the `### Component state prop guidelines` section of `contributing/wc-guidelines`.
- No reviews necessary for this one.
> docs(contributing/wc-guidelines): fix component state example

- package-lock.json
- package.json
Fixes #1203 
- Upgrades `lit` from `2.3.1` to `3.2.1` (no impact on our code, see [Lit 3 upgrade guide](https://lit.dev/docs/releases/upgrade/) for more info),
- Upgrades dependencies that also depend on `lit` to latest:
- `@open-wc/testing` from `3.1.6` to `4.0.0` (no impact on our code, see [@open-wc/testing releases](
https://github.com/open-wc/open-wc/releases?q=open-wc%2Ftesting&expanded=true) for more info),
- `@lit-labs/motion` from `1.0.3` to `1.0.7` (no impact on our code, see [\@lit-labs/motion releases](
https://github.com/lit/lit/releases?q=lit-labs%2Fmotion&expanded=true) for more info),
- `@lit-labs/virtualizer` from `2.0.12` to `2.0.14` (no impact on our code, see [\@lit-labs/virtualizer releases](
https://github.com/lit/lit/releases?q=virtualizer&expanded=true) for more …
> lit: upgrade to 3.2.1

- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1231
- Changes texts in the DNS section to make it more obvious that APEX domains should rely on A records instead of CNAME records,
- Check the default story in preview et read the texts in there :wink:,
- 1 reviewer from the frontend team should be enough.
Thanks @davlgd for coming up with the texts :heart:
> feat(cc-domain-management): make APEX domain DNS config more explicit

- src/components/cc-addon-admin/cc-addon-admin.js
- src/components/cc-addon-backups/cc-addon-backups.js
- src/components/cc-block-section/cc-block-section.stories.js
- src/components/cc-block/cc-block.js
- src/components/cc-domain-management/cc-domain-management.js
- src/components/cc-email-list/cc-email-list.js
- src/components/cc-grafana-info/cc-grafana-info.js
- src/components/cc-invoice-list/cc-invoice-list.js
- src/components/cc-invoice/cc-invoice.js
- src/components/cc-jenkins-info/cc-jenkins-info.js
- src/components/cc-matomo-info/cc-matomo-info.js
- src/components/cc-orga-member-list/cc-orga-member-list.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.js
Fixes #1259
- adds css rules to the `slot name="content-body"` in the `cc-block` component,
- adapt the stories of the `cc-block-section` using the slot,
- adapt other components using the slot.
- check the code,
- check the stories on the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-block-section/fix-separation-line/index.html) and compare with the [prod](https://www.clever-cloud.com/doc/clever-components/?path=/docs/readme--docs).
> fix(cc-block): add css rules to the slot name="content-body

- .git-blame-ignore-revs
Fixes #1270
- Adds the following commits to the list of commits to be ignored by `git blame`:
```
a166f4f8da4902a37bf7ef9654186c9b6ef442c4
f9fcd572efca5301e44ae348ec5eb2c41b37e931
79f7a4893dfb5194a2fb06d781c67766a5aa9349
```
People have to run `git config blame.ignoreRevsFile .git-blame-ignore-revs` to benefit from this.
No reviews necessary for this one.
> chore(git): add `git-blame-ignore-revs` file

- src/components/cc-addon-backups/cc-addon-backups.js
- src/components/cc-addon-linked-apps/cc-addon-linked-apps.stories.js
Fixes #1269 
Fixes #1268 
Fixes #1267 
- Updates the docs of `cc-addon-backups` so that the documented default display matches the reality (`block` and not `grid`),
- Sets `max-height` & `overflow: auto` to `cc-addon-backups` overlays so that their content can still be accessed when viewport is narrow.
- Move `@typedefs` comments in the `cc-addon-linked-apps` stories to fix the Storybook docs.
- Check the preview ([`cc-addon-backups`](https://clever-components-preview.cellar-c2.services.clever-cloud.com/misc/small-component-fixes/index.html?path=/story/%F0%9F%9B%A0-addon-cc-addon-backups--default-story) with reduced viewport width & height, [`cc-addon-linked-apps`](https://clever-components-preview.cellar-c2.services.clever-cloud.com/misc/small-component-fixes/index.html? …
> Small component fixes

- src/components/cc-domain-management/cc-domain-management.js
Fixes #1261
The "Configure your DNS" section used to display a loader / error message depending on its state but it no longer does
This PR restores the error message / loader display depending on the state.
- Check the preview ([loading](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-domain-management/fix-dns-config-state/index.html?path=/story/%F0%9F%9B%A0-domains-cc-domain-management--loading) & [error](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-domain-management/fix-dns-config-state/index.html?path=/story/%F0%9F%9B%A0-domains-cc-domain-management--error)),
> fix(cc-domain-management): restore loader & error message in the DNS config section

- src/stories/cc-pricing-page-sandbox.js
- In the `cc-pricing-page` stories, removes irrelevant features that we don't want to display (and we don't really want to advertise these features anyway because the API sends incorrect info about them).
This is ISO with what we had before the last update: https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-domain-management/pocs/index.html?path=/story/%F0%9F%9B%A0-pricing-cc-pricing-page--default-story
- Check the story,
> refactor(cc-pricing-page-sandbox): filter out irrelevant features

- src/components/cc-tile-status-codes/cc-tile-status-codes.js
- src/components/cc-tile-status-codes/cc-tile-status-codes.smart.js
- src/components/cc-tile-status-codes/cc-tile-status-codes.stories.js
* This PR filters out `0` status codes returned by the backend.
* It's a really small PR, one reviewer should be enough. :wink: 
* Check the code
* Test on a local storybook on the `/demo-smart` page that the `0` status codes are filtered.
> chore(cc-tile-status-codes): filter out status codes below `100`

- .storybook/preview.js
- eslint/javascript/eslint-config-clever-cloud-esm.js
- src/stories/lib/make-story.js
- Enables two rules from the `import` plugin in `eslint-config-clever-cloud-esm`:
- `no-unresolved`: even though TypeScript already handles this fairly well, it's better to be safe than sorry + the config is meant to be generic and could be used in projects that don't have TypeScript enabled (thanks @Galimede for pointing that out),
- `extensions`: same reason as above but TypeScript doesn't always handle the extension requirement (for plain imports like `import './my-component.js';`.
The `named` remains disabled because it doesn't seem to work well. We'll deal with that when we handle #1273 
- Checking the code should be enough,
- You can go to a component file and remove some extensions from imports if you want to see it working,
- 1 reviewer is enough for this one.
> eslint: enable some rules from the import plugin in the generic clever cloud config

- .storybook/preview.js
- cem/generate-cem-vite-plugin.js
- package-lock.json
- package.json
- src/lib/i18n/i18n.types.d.ts
- src/stories/lib/make-story.js
- src/stories/lib/markdown-indexer.js
- src/stories/lib/markdown-to-csf.js
- src/stories/lib/smart-auth-plugin.js
- src/stories/lib/story-names.js
- tsconfig.ci.json
- tsconfig.json
Fixes #1245
- Fixes Type Checking issues in the `.storybook` folder and related libs,
- Adds the `.storybook` to the list of files to type check (both in editors & CI).
- Checking the code should be enough,
- 1 reviewer is enough for this one
> refactor(storybook): typecheck related libs

- .storybook/.htaccess
- .storybook/preview.js
- eslint.config.js
- Removes the `RewriteRule` that is supposed to redirect to `index.html` when an asset is not found
<details>
<summary>More info</summary>
This RewriteRule doesn't work for the prod app because the storybook assets are in `/doc/clever-components` and not directly at the root.
Ideally we would go for a `RewriteRule` that would take this into account but we cannot access the app environment variables from the `.htaccess` file so we would have to do something like this:
`RewriteRule ^ /doc/clever-components/index.html`
With this, any path after `doc/clever-components/` would be redirected to the `index.html`.
But we don't really want to maintain this hardcoded value.
Since all storybook pages rely on a queryParam on the root URL anyway, we don't really have to support this because someone …
> Storybook: remove unused `RewriteRule` from `.htaccess`

- docs/adr/adr-0027-enabling-type-checking.md
- Adds an ADR about Type Checking.
> Docs: Add ADR about Type Checking

- src/components/cc-kv-terminal/cc-kv-terminal.js
- src/components/cc-kv-terminal/cc-kv-terminal.types.d.ts
This PR moves the history of commands and their results into a lit virtualizer so that browser can handle huge command history.
- Check the code
- Use the command `command` to get huge result output
- Try to scroll up and check that you don't loose focus
- Check that when running command (hitting Enter), the view always scroll to bottom properly
- Verify on all browsers
> fix(cc-kv-terminal): handle huge command history using lit-virtualizer

- src/components/cc-addon-admin/cc-addon-admin.js
- src/components/cc-button/cc-button.js
- src/components/cc-domain-management/cc-domain-management.js
- src/components/cc-email-list/cc-email-list.js
- src/components/cc-env-var-form/cc-env-var-form.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.js
Fixes #1124
- Makes the `cc-button` throw an error if both `waiting` and `disabled` are set to `true` at the same time.
- The question is: is it a good idea to throw an error and is it a good idea to do so in the lit lifecycle? 
- The goal was to make it obvious that something is not right. Throwing an error is not enough because it won't make the tests fail + it won't be visible (the underlying issue is very easy to miss).
- Throwing in the lifecycle actually breaks the component so I thought it was a good way to make it obvious that something is wrong but maybe it's not a good idea?
- Fixes all occurrences where both `waiting` and `disabled` were used at the same time on a `cc-button`.
- Compare the impacted component stories (there should be no visual changes):
- …
> cc-button: avoid setting both `disabled` & `waiting` at the same time

- eslint/lit/eslint-config-lit-clever-cloud.js
- src/components/cc-zone-picker/cc-zone-picker.js
Fixes #1265
- Enables some ESLint rule to prevent devs from using the `checked` attribute and force them to use the `checked` property instead,
- Fixes the `cc-zone-picker` component to use the `checked` property instead of the attribute.
- It should be enough considering the changes, no need to do more.
> Use the `checked` property instead of the attribute

- src/components/cc-zone-picker/cc-zone-picker.js
* This PR changes the event from `@change` to `@input`
* A `@change` event on a fieldset won't work reliably because the fieldset element itself doesn't emit change events directly. 
* This caused some value desync while working on the creation tunnel in the console
* Check the code
* Check the preview
* One reviewer should be enough
> fix(cc-zone-picker): use `@input` instead of `@change` for event

- src/components/cc-grafana-info/cc-grafana-info.js
Fixes #1124
- Adapts the `cc-grafana-info` component so that `disabled` & `waiting` are never set to `true` at the same time. I simply forgot to handle this component in #1297.
How am I sure no other components are missing?
The following log appears in local tests when there are issues of this type:
> `waiting` and `disabled` cannot be set to true at the same time, see https://github.com/CleverCloud/clever-components/issues/1124 for more info
This time I ran all component tests locally and searched for the message to make sure there was none left.
**Note**: ideally I'd like these errors to make tests fails but I'm not sure how to do that at the moment? If you have ideas feel free to weigh in!
**Note**: this is a `refactor` commit and not a `fix` because the issue it fixes has not been …
> refactor(cc-grafana-info): avoid setting both `disabled` & `waiting` at the same time

- src/components/cc-kv-terminal/cc-kv-terminal.js
Fixes #1311
- Catches `disconnected` errors inside the `updated` lifecycle of `cc-kv-terminal`. These errors seem to happen when the component is removed from the DOM but a scrolling promise is pending?
**Note**: this is a `refactor` commit and not a `fix` because the issue it fixes has not been released yet. 
- Run `npm run test src/components/cc-kv-terminal/cc-kv-terminal.test.js`, you should only have `Resize Observer` logs. (the resize observer logs will soon be gone, I handled this subject when refactoring a11y tests).
> refactor(cc-kv-terminal): catch `disconnected` errors

- src/components/cc-plan-item/cc-plan-item.js
- src/components/cc-plan-item/cc-plan-item.stories.js
- src/components/cc-plan-item/cc-plan-item.test.js
- src/components/cc-plan-item/cc-plan-item.types.d.ts
- src/components/cc-plan-picker/cc-plan-picker.js
- src/components/cc-plan-picker/cc-plan-picker.stories.js
- src/components/cc-plan-picker/cc-plan-picker.test.js
- src/components/cc-plan-picker/cc-plan-picker.types.d.ts
- src/stories/fixtures/plans.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
This PR introduces three new components for the new creation-tunnel:
* `cc-plan-item` => The base plan card
* `cc-plan-picker` => One plan picker 
* `cc-plan-configurator` => The form control element where you can refine your choice with two pickers
* Check the code
* Check the stories
> feat(creation-tunnel): init plan components

- src/components/cc-kv-terminal/cc-kv-terminal.js
- src/styles/accessibility.js
* This PR reverts the changes that were initially fixing the issue #1200 
* Instead we're directly making the fix on `cc-kv-terminal`
* While using `top: 0px` works and fixes the problem for `cc-kv-terminal`, it caused problems on other components using the `visually-hidden` styles, especially `cc-zone-picker` and `cc-plan-picker`
* It made these components scroll to top as the inputs were not correctly positioned anymore.
* That's why this PR reverts the fix and fixes `cc-kv-terminal` directly instead.
* Check the code
* Ideally check the sandbox of `cc-kv-explorer` to be sure that the problem doesn't appear anymore.
> fix: revert `top` a11y visually-hidden style

- docs/adr/adr-0029-issues-with-the-disabled-attribute.md
- docs/contributing/wc-guidelines.md
- Adds an ADR about the `disabled` attribute issues,
- Adds a section in `wc-contributing` to explain when to use `readonly`, `waiting` and `disabled`.
> Docs: add ADR about `disabled` attributes

- src/components/cc-env-var-form/cc-env-var-form.js
Fixes #1327
- Adds a public `hasUnsavedModifications` getter so we can use it to trigger a navigation guard in the console.
> feat(cc-env-var-form): add public `hasUnsavedModifications` getter

- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #970 
- Changes the link redirecting to the doc present in the `cc-env-var-form.description.exposed-config` translation key.
- Check the story `Data loaded (context exposed config)` in the preview.
- 1 reviewer should be enough.
> fix(cc-env-var-form): link exposed-config change

- src/components/cc-addon-backups/cc-addon-backups.js
Fixes #1334
- Adds a high `z-index` value to make sure the modal is displayed over any other content
- I chose to go for `9999` because I cannot anticipate if there are other z-index values within the console. This is not something I like to do but since it's a temporary fix, I think it's fine :shrug: 
> fix(cc-addon-backups): make sure overlays are displayed on top of everything

- src/components/cc-ssh-key-list/cc-ssh-key-list.js
Fixes #1262
Reduce the spacing below the first section by rearranging the margins and gaps in the cc-block info slot
Check the commits,
Check the `cc-ssh-key-list` stories in the preview.
1 reviewer should be enough.
> fix(cc-ssh-key-list): reduce spacing below the first section

- src/components/cc-addon-elasticsearch-options/cc-addon-elasticsearch-options.js
- src/components/cc-addon-elasticsearch-options/cc-addon-elasticsearch-options.stories.js
- src/components/cc-tile-scalability/cc-tile-scalability.js
- src/components/cc-tile-scalability/cc-tile-scalability.stories.js
- src/components/common.types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1172 
Fixes #1230
- Changes the format of `monthlyCost` from a simple number to an object that accepts a `currency` as well as some `amount`.
- Makes `monthlyCost` optional so that the component does not try to display any price in case no `monhtlyCost` is provided for a flavor (when billing is disabled).
- Check the [stories in preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-addon-elasticsearch-options/support-multi-currency/index.html?path=/story/%F0%9F%9B%A0-addon-cc-addon-elasticsearch-options--default-story) (especially the new ones).
> cc-addon-elasticsearch-options: support multi-currency and no monthly cost

- src/components/cc-orga-member-card/cc-orga-member-card.js
- src/components/cc-orga-member-card/cc-orga-member-card.stories.js
- src/components/cc-orga-member-card/cc-orga-member-card.types.d.ts
- src/components/cc-orga-member-list/cc-orga-member-list.js
- src/components/cc-orga-member-list/cc-orga-member-list.smart.js
- src/components/cc-orga-member-list/cc-orga-member-list.stories.js
- src/components/cc-orga-member-list/cc-orga-member-list.types.d.ts
- src/stories/fixtures/long-member-list.js
Fixes #1164
- Migrates the `cc-orga-member-list` component to the new state API.
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-orga-member/migrate-to-new-state/index.html?path=/story/%F0%9F%9B%A0-organisation-cc-orga-member-list--default-story) vs [prod](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-organisation-cc-orga-member-list--default-story) stories,
- Run locally and check `demo-smart` to see if all features still work properly,
- 3 reviewers would be nice (breaking change + smart impact, better safe than sorry).
> refactor(cc-orga-member-list)!: rework properties to avoid impossible 

- src/components/cc-ssh-key-list/cc-ssh-key-list.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.smart.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.stories.js
- src/components/cc-ssh-key-list/cc-ssh-key-list.types.d.ts
Fixes #1165
- Migrates the `cc-ssh-key-list` component to the new state API.
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-ssh-key-list/migrate-to-new-state/index.html?path=/story/%F0%9F%9B%A0-profile-cc-ssh-key-list--default-story) vs [prod](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-profile-cc-ssh-key-list--default-story) stories,
- Run locally and check `demo-smart` to see if all features still work properly (I couldn't check for accounts that are linked to GitHub because it seems the CLI oAuth Consumer is not allowed to fetch data for such cases, the error is already present in master even though it works fine in the console, which makes me think it's related to the CLI oAuth …
> refactor(cc-ssh-key-list)!: rework properties to avoid impossible states

- src/components/cc-email-list/cc-email-list.js
- src/components/cc-email-list/cc-email-list.smart.js
- src/components/cc-email-list/cc-email-list.stories.js
- src/components/cc-email-list/cc-email-list.types.d.ts
Fixes #1163
- Migrates the `cc-email-list` component to the new state API.
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-email-list/migrate-to-new-state/index.html?path=/story/%F0%9F%9B%A0-profile-cc-email-list--default-story) vs [prod](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%9B%A0-profile-cc-email-list--default-story) stories,
- Run locally and check `demo-smart` to see if all features still work properly,
- 3 reviewers would be nice (breaking change + smart impact, better safe than sorry).
> refactor(cc-email-list)!: rework properties to avoid impossible states

- cem/support-typedef-jsdoc.js
Fixes #1150 
* This PR removes the log that were produced when generating doc types of a component.
* Now, only the errors when writing a `typedef` will be displayed.
* Note: we couldn't add a `--silent` flag to the plugin as the CLI parameters are handled by CEM directly. 
* Run some tests, the logs shouldn't be there anymore.
* In a component try changing a `@typedef` to something like  `@tyedef` with a typo.
* Run the script `npm run component:docs`, it should show an error.
* One or two reviewer should be enough.
> refactor(cem): silent doc generation

- src/components/cc-block-detail/cc-block-details.js
- src/components/cc-block-detail/cc-block-details.stories.js
Fix #1348 
Introduce the `cc-block-detail` component. This component displays more information in the `cc-block` footer as command lines.
- Check the code
- Check the stories in the preview
- Check if the design is close enough to the [wireframe](https://www.figma.com/design/rC5NuHHEZ1E7HEEAbQyvuq/CC-Block-new?node-id=8-771&t=SkZ82Je83zrQ47OH-1) made by Marion
> feat(cc-block-detail): init cc-block-detail component

- sandbox/cc-logs-app-runtime/cc-logs-app-runtime-sandbox.js
- src/components/cc-logs-app-runtime/cc-logs-app-runtime.js
- src/components/cc-logs-control/cc-logs-control.js
- src/components/cc-logs-control/cc-logs-control.stories.js
- src/components/cc-logs-date-range-selector/cc-logs-date-range-selector.js
- src/components/cc-logs-date-range-selector/cc-logs-date-range-selector.stories.js
- src/components/cc-popover/cc-popover.js
* When user selects a `custom` date range, a form containing the `since` and the `from` date inputs is displayed under the selector.
* This makes the component having a column based layout
* This layout fits well in the `cc-logs-app-runtime` component because it has got a left panel with the instances.
* But it doesn't fit with the future `cc-logs-addon-runtime` component which doesn't have a left column.
* It also wont fit the `cc-logs-app-access` component when we will integrate a date selection in it.
The main purpose of this PR is to change how the custom date range form is display inside the `cc-date-range-selector` component.
For the moment I left all the a11y considerations apart, I know there are a lot to do but this will be done in another PR.
So there are several commits:
* …
> feat(cc-date-range-selector): move custom date range form inside popover body

- src/components/cc-order-summary/cc-order-summary.js
- src/components/cc-order-summary/cc-order-summary.stories.js
- src/components/cc-order-summary/cc-order-summary.types.d.ts
Fixes #1346
For each line of the "configuration" part (aka the main part):
- Adds a `skeleton` property 
- Adds a `ariaLive` property
- Check the stories in [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-order-summary/improve-configuration-item/index.html?path=/story/%F0%9F%9A%A7-beta-%F0%9F%9B%A0-creation-tunnel-cc-order-summary-beta--default-story), especially the "Skeleton" and "With aria live" ones.
Two should be enough, with a mandatory one from @florian-sanders-cc. :hand_with_index_finger_and_thumb_crossed: 
At some point, I considered making skeleton state on label & value separately but I'm not sure if it's worth the complexity. Maybe later if really needed.
> feat(cc-order-summary): improve configuration item implementation

- .github/workflows/test-and-build.yml
This PR adds a check on the commit(s) message(s), ensuring that they respect conventional commit format.
If one doesn't activate the local git hook that ensures conventional commit messages, the CI will be there to verify it anyway.
* pull this branch
* add a commit with an invalid message (use `--no-verify` option in the commit command to bypass the local git hook)
```
git commit --no-verify -m "invalid message"
```
* push
* See the Tests and build job fail.
* Please remove your commit and force push afterward ;)
> ci(code-quality): add a check on the commit messages

- sandbox/cc-logs-app-access/cc-logs-app-access-sandbox.js
- src/components/cc-logs-app-access/cc-logs-app-access.js
- src/components/cc-logs-app-access/cc-logs-app-access.smart.js
- src/components/cc-logs-app-access/cc-logs-app-access.smart.md
* This PR adds a date range selector to the `cc-logs-app-access`.
* It allows also to set the date range from the smart context, so that we will be able to store and restore date range selection using the Settings API.
* check the stories
* check the sandbox
> feat(cc-logs-app-access): add date range selector

- package-lock.json
- package.json
- sandbox/cc-logs-addon-runtime/cc-logs-addon-runtime-sandbox.js
- sandbox/index.js
- src/components/cc-logs-addon-runtime/cc-logs-addon-runtime.js
- src/components/cc-logs-addon-runtime/cc-logs-addon-runtime.smart.js
- src/components/cc-logs-addon-runtime/cc-logs-addon-runtime.smart.md
- src/components/cc-logs-addon-runtime/cc-logs-addon-runtime.stories.js
- src/components/cc-logs-addon-runtime/cc-logs-addon-runtime.types.d.ts
- src/components/cc-logs-app-access/cc-logs-app-access.smart.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
This PR adds `cc-logs-addon-runtime` component that displays addon logs
* check the stories
* check the sandbox
> feat(cc-logs-addon-runtime): init component

- src/components/cc-logs-addon-runtime/cc-logs-addon-runtime.js
This PR dispatch `cc-logs-addon-runtime:options-change` event with the merged options payload.
> feat(cc-logs-addon-runtime): dispatch `cc-logs-addon-runtime:options-change` event

- src/components/cc-logs-app-runtime/cc-logs-app-runtime.js
- src/components/cc-logs-app-runtime/cc-logs-app-runtime.smart.js
- src/components/cc-logs/cc-logs.js
Fixes #1366 
There is also an additional commit that I wanted to tackle a long time ago. It is more like a workaround to something I don't understand with `lit-virtualizer`. Sometimes, `lit-virtualizer` asks for a `null` item to be rendered.
* Use the sandbox
* Select live mode
* Play with instance selection
* Instance selection should not be reset when new logs arrive
> fix(cc-logs-app-runtime): fix instance selection in live mode

- .prettierrc
- sandbox/cc-logs-app-access/cc-logs-app-access-sandbox.js
- src/components/cc-block-detail/cc-block-details.stories.js
- src/components/cc-grafana-info/cc-grafana-info.smart.js
- src/components/cc-logs-addon-runtime/cc-logs-addon-runtime.js
- src/components/cc-logs-app-access/cc-logs-app-access.smart.js
- src/components/cc-logs-app-runtime/cc-logs-app-runtime.smart.js
- src/components/cc-logs-app-runtime/cc-logs-app-runtime.stories.js
- src/components/cc-logs-date-range-selector/cc-logs-date-range-selector.js
- src/components/cc-logs-instances/cc-logs-instances.stories.js
- test-mocha/prettier/sort-lit-get-properties.test.js
* This PR disables temporarily the plugin that sorts the Lit properties in our components.
* This has been done because Prettier can't handle multiple plugins that modify its AST.
* That's why we decided to remove the Lit properties sort plugin in favor for the import one for now.
* The PR also sorts the unsorted imports due to the plugin not functioning.
* Note: We plan to activate the Lit sort plugin again when we'll find a workaround. 
* Check the code.
* Do a `npm run format:check`, no warnings should come out.
* 2 reviewers should be enough.
> chore(prettier): remove Lit property sorting plugin from Prettier config

- src/components/cc-token-session-list/cc-token-session-list.js
- src/components/cc-token-session-list/cc-token-session-list.smart.js
- src/components/cc-token-session-list/cc-token-session-list.smart.md
- src/components/cc-token-session-list/cc-token-session-list.stories.js
- src/components/cc-token-session-list/cc-token-session-list.types.d.ts
- src/lib/i18n/i18n.types.d.ts
- src/lib/tokens.js
- src/lib/tokens.types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
- test/tokens/tokens.test.js
Fixes #1360
- Adds a `cc-session-tokens` component
> [!IMPORTANT]
>  - We don't have info about the user agent / IP address of the session so we can only show the dates,
>  - The component doesn't handle expired tokens because the API is only supposed to provide alive sessions,
>  - There can only be one current session and there should always be one. It's very difficult to reflect this with types:
>    - I do have something that gets really close to that with recursive types but it's difficult to read so I chose to stay simple,
>    - We could add something to throw an error if we don't have 1 (exactly 1) current session at runtime. (Usually it's not something we do but I've broken the smart a few times when refactoring :shrug:).
>  - The list of sessions can never be empty since there's …
> feat(cc-session-tokens): init

- src/lib/logs/logs-stream.js
- test/logs/logs-stream.test.js
When connecting to a log stream, we create a timer that waits for the first log to come. When the first log comes before the timeout, everything is fine. If the timeout elapses with no log, we do the following:
- in live mode, we display a waiting message and let the stream open.
- in cold mode, we consider that there is no log in the selected time range and we stop the SSE.
The actual timeout is set to 2 seconds.
In fact, when using cold mode, it can happen that the first log comes way after those two seconds.
So we need to wait a bit more time in cold mode before considering that there are no logs in the selected time range.
* This PR allows to use a different timeout when in cold or live mode.
* It keeps the 2 seconds timeout for live mode
* It uses an 8 seconds timeout for cold mode
* …
> feat(cc-logs-*): set a longer timeout when waiting first log in cold mode

- src/components/cc-zone/cc-zone.js
- src/components/cc-zone/cc-zone.stories.js
- Show the `displayName` of a zone when it's defined (even if it does not have a `scope:private` tag)
- Rework the stories to reflect better this modified behavior
- Rework the stories to reflect better the inline display of the cc-zone in headers
- look at the cc-zone stories
- look at the cc-zone-input stories
The zone with a `displayName` should show this instead of "City, Country".
> feat(cc-zone): use diplayName when it's defined

- src/components/cc-token-oauth-list/cc-token-oauth-list.js
- src/components/cc-token-oauth-list/cc-token-oauth-list.smart.js
- src/components/cc-token-oauth-list/cc-token-oauth-list.smart.md
- src/components/cc-token-oauth-list/cc-token-oauth-list.stories.js
- src/components/cc-token-oauth-list/cc-token-oauth-list.types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1369 
- Adds a `cc-token-oauth-list` component
> [!IMPORTANT]
>  - The component doesn't handle expired tokens because the API is only supposed to provide alive OAuth tokens,
>  - There is no sandbox / demo-smart because only almighty consumers may list tokens.
>  - You can probably skip the CSS code review since it's almost exactly the same as the session token component (I'll try to refactor all of this in a flexible `cc-token-card` component afterwards).
- check all the stories within the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-session-tokens/init/index.html?path=/story/%F0%9F%9B%A0-profile-cc-token-oauth-list--default-story),
- proceed with the QA in the usual google drive :wink:
> `cc-token-oauth-list`: init

- src/components/cc-token-oauth-list/cc-token-oauth-list.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1416
- Adds a doc link to the `cc-block` footer in the `cc-token-oauth-list` component.
Note that the fact we have to add CSS to `[slot="link"]` is not ideal because it should probably be done by the `cc-block` component but this will be solved with the `cc-link` component anyway.
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-token-oauth-list/add-doc-link-to-cc-block-footer/index.html?path=/story/%F0%9F%9B%A0-profile-cc-token-oauth-list--default-story),
- 1 reviewer is enough.
> feat(cc-token-oauth-list): add doc link to `cc-block` footer

- demo-smart/index.html
- src/components/cc-token-api-creation-form/cc-token-api-creation-form.events.js
- src/components/cc-token-api-creation-form/cc-token-api-creation-form.js
- src/components/cc-token-api-creation-form/cc-token-api-creation-form.smart.js
- src/components/cc-token-api-creation-form/cc-token-api-creation-form.smart.md
- src/components/cc-token-api-creation-form/cc-token-api-creation-form.stories.js
- src/components/cc-token-api-creation-form/cc-token-api-creation-form.types.d.ts
- src/components/cc-token-api-list/cc-token-api-list.smart.js
- src/components/cc-token-api-list/cc-token-api-list.smart.md
- src/lib/date/date-utils.js
- src/lib/date/date.types.d.ts
- src/lib/events-map.types.d.ts
- src/lib/send-to-api.types.d.ts
- src/lib/send-to-auth-bridge.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- tsconfig.json
Fixes #1395 
- Adds a new `cc-token-api-creation-form` component that relies on 3 steps:
- configuration form: the user provides info about the token they want to create (name, desc, duration or expiration date),
- no API call on submit, only client-side validation,
- validation form: the user provides the credentials required to validate the creation of the token,
- client-side validation to prevent empty values + API call & validation about the credentials,
- the user can go back to the config step if they want (by clicking the "configuration" step in the nav, or the link on the left of the submit button),
- copy token: the created token is displayed in a cc-input-text with the `secret` option so the value is hidden by default,
- the user cannot go back to previous steps because the …
> `cc-token-api-creation-form`: init

- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1037
Fixes #1038
- Removes trailing `.` at the end of error messages,
- Removes "Please" / "Veuillez" inside error messages.
- You could also check the preview if you want but I feel like it's overkill for this one?
- 1 reviewer is enough.
> refactor(translations): remove trailing dots and "please" inside error messages

- src/components/cc-token-api-list/cc-token-api-list.js
- src/components/cc-token-api-list/cc-token-api-list.smart.js
- src/components/cc-token-api-list/cc-token-api-list.smart.md
- src/components/cc-token-api-list/cc-token-api-list.stories.js
- src/components/cc-token-api-list/cc-token-api-list.types.d.ts
- src/components/common.events.js
- src/lib/events-map.types.d.ts
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1431
- Handles cases where the user has no password set (account created through GitHub),
- Replaces the "Create new token" button with a notice inviting the user to add a password to their account,
- Adds a "Add a password" button that sends a password request to the user email when clicking on the button.
- Check the new stories,
- Check the demo-smart if you want (you'll need an account with no password or you'll need to override the call through the network tab - ping me if you need help)
> feat(cc-token-api-list): handle users with no password set

- src/components/cc-input-text/cc-input-text.js
Fixes #1227
- Add the possibility to use `cmd+Enter` on mac OS
> fix(cc-input-text): add the possibility to use command key on implicit submit

- src/components/cc-block/cc-block.js
Fixes #1351 
- Update the component to use the same animation on hover & toggle as in `cc-block-details`
- Check the cc-block toggle stories, within the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/fix/update-animation-toggle/index.html?path=/story/%F0%9F%A7%AC-molecules-cc-block--toggle-open),
> fix(cc-block): update animation on hover & toggle

- src/components/cc-input-number/cc-input-number.stories.js
- src/components/cc-input-text/cc-input-text.stories.js
- src/components/cc-select/cc-select.stories.js
- src/translations/translations.en.js
Fixes #1447
- Reworks error stories of form elements to use `reportInlineValidity` on inputs,
- Simplifies the error stories to only display one case,
- Adds error stories with invalid format,
- Removes impossible states (ex : required inputs with a valid value and empty error message),
- Removes "." at the end of simple sentence.
- Check to commits,
- Check the preview stories and compare with prod.
- On the `cc-input-text`, I figured out that a component with `multi` prop can not be visually seen with expended input and an error message (as the input expends regarding the text added inside and the empty error message is triggered on empty input). I have left the example of a `cc-input-text` multilines on the `customLabelStyle` story, but we can not see it anymore on error mode as it is …
> fix(form elements): use reportInlineValidity in error stories

- package-lock.json
- package.json
- src/components/cc-input-date/cc-input-date.js
- src/styles/shoelace.js
* This PR bumps the prettier version to 3.6.0
* This version supposedly introduces a (experimental) new and faster CLI
* Though we can't use it yet as it only supports string plugins
* Check the commits
* Let the ci do its job
* You can run `npm run format:check` anyway if you want to test it
* One reviewer is enough
> chore(prettier): bump prettier to 3.6.0

- src/components/cc-input-date/cc-input-date.js
- src/components/cc-input-date/cc-input-date.stories.js
- src/components/cc-logs-date-range-selector/cc-logs-date-range-selector.js
- src/components/cc-token-api-creation-form/cc-token-api-creation-form.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
Fixes #1455
Fixes #1456
- Refactors the `cc-input-date` render to always display the help message,
- Removes the unnecessary `helpMessage` and `errorMessageWithHelpMessage` stories,
- Formats the underflow and overflow date ranges,
- Adds a `errorMessageInvalidRangeOverflowAndUnderflow`.
- Check the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/refactor/cc-input-date-improve-format-displayed/index.html?path=/docs/%F0%9F%A7%AC-atoms-cc-input-date--docs) and compare with [prod](https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%A7%AC-atoms-cc-input-date--default-story),
- Look for any visual regression on different screen sizes, especially on impacted components (`cc-logs-date-range-selector` and …
> refactor(cc-input-date): improve format displayed

- cem/sort-items.js
Fixes #1025
- Sorts CEM modules so we can diff manifests easily.
- Without this change, only properties inside each modules are sorted so when you generate a manifest, you sometimes end up with `cc-addon-admin` being the first module and sometimes `cc-addon-elasticsearch-options` instead.
- Run `npm run components:docs`,
- Copy the result `dist/custom-elements.json` to somewhere outside `dist` so it doesn't get erased,
- Run `npm run components:docs` again,
- Copy the result again,
- Diff the two files: `diff custom-elements-1.json custom-elements-2.json` => there should be no changes,
- 1 reviewer (@Galimede) should be enough for this one!
> refactor(cem/sort-items): sort modules to make diffing easier

- cem/support-typedef-jsdoc.js
- package-lock.json
- package.json
- src/lib/utils.js
* This PR makes use of the latest TS version for our typedef plugin
indtead of the one provided by CEM.
* Check the commits
* Run `npm components:docs` or check the preview
* In storybook you should still see the types in the docs section of the components.
> cem: adapt plugin to use latest version of TS

- src/components/cc-input-text/cc-input-text.js
* This PR reverts and set the initial margin for the buttons instead of doing `align-items: center` in the `cc-input-text`
* This caused the `cc-clipboard` to be aligned vertically in the center of the `cc-input-text` on mutli mode.
* Check the commit
* Check the preview
* Two reviewers should be enough
> fix(cc-input-text): align back button correctly on multi

- demo-smart/index.html
- src/translations/translations.fr.js
Fixes #1508
- Fixes the delete feature (ES Add-on) in French for the `cc-addon-backups` component (this bug is actually very old, it hasn't been working since 2021 :see_no_evil:)
- Check the [`cc-addon-backups` - Data Loaded (new elasticsearch) in prod](https://www.clever.cloud/developers/clever-components/?path=/story/%F0%9F%9B%A0-addon-cc-addon-backups--data-loaded-with-new-elasticsearch&globals=locale:fr) vs [`cc-addon-backups` - Data Loaded (new elasticsearch) in preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-addon-backups/fix-deletion-feature/index.html?path=/story/%F0%9F%9B%A0-addon-cc-addon-backups--data-loaded-with-new-elasticsearch&globals=locale:fr).
> fix(cc-addon-backups): allow using the delete feature in french

- src/components/cc-block-details/cc-block-details.js
- stylelint.config.js
Fixes #1450
- Improves the responsive aspect of `cc-block-details` by using container queries.
- Check the preview vs prod.
> fix(cc-block-details): improve responsive

- src/components/cc-env-var-form/cc-env-var-form.smart-env-var-app.js
Fixes #1520
- Relies on a standard toast with timeout for the restart feature within the `cc-env-var-form.smart-env-var-app` component.
The toast contains a link which is why I went for no timeout initially but the link is available from the menu anyway and it's annoying to force users to close this toast manually in this case.
- Run locally and go check the `demo-smart` > env-var-form-app > app-node,
- Modify  or add some env var, update and then restart using the button => the toast should have the default timeout.
- 1 reviewer is enough for this one.
> fix(cc-env-var-form.smart-env-var-app): set timeout for restart toast

- package-lock.json
- package.json
- rollup/rollup-common.js
The lit labs plugin made rollup treat the config as CJS instead of ESM and crash when trying to install the components locally from the console3 project:
```
[!] Error: While loading the Rollup configuration from "rollup/rollup-npm.config.js", Node tried to require an ES module from a CommonJS file, which is not supported. A common cause is if there is a package.json file with "type": "module" in the same
folder. You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content, which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.
https://rollupjs.org/guide/en/#using-untranspiled-config-files
Error: While loading the Rollup configuration from "rollup/rollup-npm.config.js", Node tried to …
```
> refactor(rollup-common): replace `@lit-labs/rollup-plugin-minify-html-literals`

- demo-smart/index.html
- src/components/cc-addon-header/cc-addon-header.events.js
- src/components/cc-addon-header/cc-addon-header.js
- src/components/cc-addon-header/cc-addon-header.smart-keycloak.js
- src/components/cc-addon-header/cc-addon-header.smart-keycloak.md
- src/components/cc-addon-header/cc-addon-header.stories.js
- src/components/cc-addon-header/cc-addon-header.types.d.ts
- src/lib/events-map.types.d.ts
- src/stories/fixtures/addon.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- add a `cc-addon-header` component,
- add addon fixtures,
- add `cc-addon-header` to demo-smart.
- check the commits,
- check the stories in the [preview](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-addon-header/init/index.html?path=/docs/%F0%9F%9B%A0-addon-cc-addon-header--docs),
- QA is available on [Notion](https://www.notion.so/cc-header-addon-beta-23ffe1a33d3880c6b080deef2a09e6a3).
> feat(cc-addon-header): init component

- src/components/cc-link/cc-link.js
When the `download` attribute is set on the `cc-link`, the `cc-icon` was always display on the right of the text, but we only want this icon to be displayed when the `cc-link` mode is set to `default` and not when the mode is set to `button` or `subtle`. This PR fixes that.
- Check and inspect the [download story.](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-link/fix-download-icon/index.html?path=/story/%F0%9F%A7%AC-atoms-cc-link--download-link)
1 reviewer is enough.
> fix(cc-link): only display download `cc-icon` on default mode

- src/components/cc-addon-header/cc-addon-header.js
- src/components/cc-addon-header/cc-addon-header.stories.js
- src/components/cc-addon-header/cc-addon-header.types.d.ts
- src/stories/fixtures/addon.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- Adds `configLink` property to the state,
- Adds Kubernetes product to the stories.
- Check the stories, espacially the [Kubernetes ones](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-addon-header/add-kube/index.html?path=/docs/%F0%9F%9B%A0-addon-cc-addon-header--docs)
1 reviewer should be enough.
> feat(cc-addon-header): add Kubernetes

- demo-smart/index.html
- src/components/cc-env-var-form/cc-env-var-form.js
- src/components/cc-env-var-form/cc-env-var-form.stories.js
- src/components/cc-env-var-form/cc-env-var-form.types.d.ts
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.js
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart-addon.js
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart-addon.md
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart-app.js
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart-app.md
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart.js
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.smart.md
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.stories.js
- src/components/cc-env-var-linked-services/cc-env-var-linked-services.types.d.ts
This PR adds some CLI usage examples in the cc-env-var-form footer of every linked addons/applications.
- Additionally, it adds an optimization on how the linked addons env vars are fetched. Instead of fetching addons, and then fetching env var for every addons, it uses a single fetch to the right endpoint.
- After this optimization, the need of a dedicated state for each linked service is no more needed. This PR proposes to introduce a breaking change that simplifies the `state` property shape.
- To ease integration in console, this PR splits the smart component by `type`
- check the code
- verify smart-demo locally
- verify [stories](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-env-var-linked-services/add-cli-examples/index.html?path=/story/%F0%9F%9B%A0-enviro …
> feat(cc-env-var-linked-services): display CLI examples

- src/components/cc-addon-info/cc-addon-info.js
- src/stories/fixtures/addon-info.js
- Adds `latest` to fake data objects used for `cc-addon-info` stories.
- No review necessary.
> refactor(cc-addon-info): add missing latest version in addon info stories

- tasks/visual-tests/manage-visual-tests-data.js
- The `expectationMetadata.commitSha` was renamed to `expectationMetadata.commitReference` but the
`manage-visual-tests-data.js` had not adjusted accordingly.
- No review necessary, just a renaming for CI stuff.
> ci(visual-tests): fix last expectation caching

- src/components/cc-addon-credentials-content/cc-addon-credentials-content.js
- Tweaks the CSS for labels so that they shrink progressively until they wrap (thanks @roberttran-cc for the idea :muscle:).
- Check the preview and reduce the viewport progressively for the [default story](https://clever-components-preview.cellar-c2.services.clever-cloud.com/cc-addon-credentials-beta/improve-labels-wrapping/index.html?path=/story/%F0%9F%9B%A0-addon-cc-addon-credentials-content--default-story),
> feat(cc-addon-credentials-content): make credentials labels more responsive

- .github/workflows/manage-visual-tests.yml
- The job tried to checkout the current branch of the PR but it could fail because branches are automatically deleted when the PR is merged.
- The job will now checkout master instead and provide the BRANCH_NAME to the delete script through an environment variable.
- No review required, I'll simply run the tests in this PR and merge since it has no impact on end users or security :wink:
> ci(visual-tests): prevent clean up failure

- src/components/cc-addon-credentials-beta/cc-addon-credentials-beta.smart-keycloak.js
- src/translations/translations.en.js
- src/translations/translations.fr.js
- Changes the docs URL and text for the Keycloak `cc-addon-credentials-beta` to highlight the `secured multi-instances` feature.
- Check demo-smart keycloak and click on the docs link.
> feat(cc-addon-credentials-beta): change Keycloak docs URL and text
